/* =========================================
   ASTRA AI GATEWAY v3.1
   Coach Engine + trading system + market memory + proactive vision
========================================= */
const AIGateway={
    extractAnswer(data){if(typeof data==="string")return data;if(data?.answer)return data.answer;if(data?.message)return data.message;const response=data?.response||data;if(typeof response==="string")return response;if(response?.output_text)return response.output_text;const output=response?.output;if(Array.isArray(output)){const text=output.flatMap(item=>Array.isArray(item?.content)?item.content:[]).filter(item=>item?.type==="output_text"&&typeof item?.text==="string").map(item=>item.text).join("\n");if(text)return text;}return JSON.stringify(data);},
    getTradingSystem(){const t=ASTRA.modules.trading?.strategy;if(!t)return null;return{name:ASTRA.modules.trading.name,philosophy:t.philosophy,framework:t.framework,rules:t.rules,execution:t.framework?.execution,higherTimeframe:t.framework?.higherTimeframe,fractalScaling:t.framework?.fractalScaling};},
    isTradingContext(message,extra={}){const text=String(message||"").toLowerCase();return !!(extra.trading||extra.analysis||extra.backtest||extra.liveTrading||extra.proactive||/\b(trad|trade|trading|chart|market|setup|entry|exit|liquidity|supply|demand|structure|timeframe|backtest|forex|pair|position|stop|target|risk|markup|mark up|marked|mistake|performance|gbpusd|gbp\/usd|eurusd|eur\/usd|xauusd|nas100)\b/.test(text));},
    syncNaturalState(message){
        const coach=ASTRA.modules.coach;if(!coach)return null;const text=String(message||"");const lower=text.toLowerCase();
        const pair=(text.match(/\b(?:GBP\s*\/\s*USD|EUR\s*\/\s*USD|USD\s*\/\s*JPY|AUD\s*\/\s*USD|USD\s*\/\s*CAD|USD\s*\/\s*CHF|NZD\s*\/\s*USD|XAU\s*\/\s*USD|NAS100|US30|SPX500|[A-Z]{6})\b/i)||[])[0];
        const tf=(text.match(/\b(?:1m|3m|5m|15m|30m|1h|2h|4h|6h|8h|12h|1d|1w|monthly|weekly|daily|hourly)\b/i)||[])[0];
        const info={};if(pair)info.pair=pair.replace(/\s+/g,"").toUpperCase();if(tf)info.timeframe=tf.toUpperCase();if(Object.keys(info).length)coach.setMarket(info);
        if(/\b(backtest|back testing|testing the setup)\b/i.test(lower))coach.setState("BACKTEST");else if(/\b(live trade|live trading|about to enter|in the trade)\b/i.test(lower))coach.setState("LIVE_TRADING");else if(/\b(plan|planning)\b/i.test(lower))coach.setState("PLANNING");else if(/\b(review|reviewing)\b/i.test(lower))coach.setState("REVIEW");else if(/\b(journal|journaling)\b/i.test(lower))coach.setState("JOURNAL");else if(/\b(marking up|markup|mark up|chart)\b/i.test(lower))coach.setState("MARKUP");
        const marked=text.match(/\b(?:mark(?:ed)?|marking)\s+(?:the\s+)?(?:liquidity|supply|demand|zone|high|low|level)[^.!?]*/i);if(marked)coach.addMarked(marked[0]);
        return coach.snapshot();
    },
    async ask(userMessage,extra={}){
        const tradingContext=this.isTradingContext(userMessage,extra);this.syncNaturalState(userMessage);
        const base=ASTRA.modules.context?.build?.()||{};const coach=ASTRA.modules.coach?.buildContext?.()||ASTRA.modules.coach?.context?.()||{};
        const context=Object.assign({},base,coach,extra.context||{},{astraResponseStyle:{role:"70% trading coach, 30% assistant",tone:"natural, calm, direct, conversational",priority:"short, precise, simple",vocabulary:"plain everyday words; avoid jargon and big words unless the user uses them first",length:"usually 1-4 short sentences; use bullets only when clearer",coaching:"notice useful things, point out mistakes, challenge weak reasoning, and suggest one next step",proactive:"when screen or market evidence is available, speak up about important observations without waiting for a question",liveTrading:"calm coach beside the user; focus on process and the current decision; do not lecture",backtesting:"coach the setup, rule, result, and lesson; never mix backtest results with live-trading progress",analysis:"compare visible evidence with Jay's trading system; do not invent anything",conversation:"sound like a natural conversation, not a report",avoid:"long introductions, repeated disclaimers, formal sections, filler, repeated context, unnecessary explanations",answerQuestionDirectly:true}});
        if(tradingContext){const memory=ASTRA.modules.memory;const session=memory?.recordMarketMessage?.(userMessage,extra);context.currentMarketSession=session||memory?.currentMarketSession?.()||null;context.marketMemoryInstruction="Remember the current market session. If the user asks where we were, identify the saved pair, timeframe, markup, plan, last screen analysis, and last message. Never invent missing details.";context.tradingSystem={loaded:true,source:"ASTRA.modules.trading.strategy",instruction:"Use this trading system as the user's source of truth for trading questions. Keep live trading and backtesting separate. Compare chart observations to this system before coaching.",system:this.getTradingSystem()};context.coachInstruction="Coach first. Use current state, screen observations, history, trade data, and setup checks. If the user is missing a key step, point it out briefly. Do not wait for a direct question when an important visible issue is present.";}
        let image=extra.image||null;let vision=!!extra.vision;if(!image&&ASTRA.modules.screen?.sharing&&ASTRA.modules.screen?.getFrame){image=ASTRA.modules.screen.getFrame({maxWidth:1280,quality:0.55});if(image){vision=true;context.screenContext={shared:true,frameAttached:true,instruction:"Inspect the attached current screen directly. Never claim you cannot see the screen when an image is attached. Only describe what is visible."};}}
        const payload={question:userMessage,context};if(image)payload.image=image;if(vision)payload.vision=true;const api=ASTRA.modules.api;if(!api?.status?.().configured){if(!extra.proactive)AstraReply("AI Gateway ready. Configure ASTRA.modules.api first.");return{configured:false,payload};}
        try{const data=await api.request("",{method:"POST",body:JSON.stringify(payload)});const answer=this.extractAnswer(data);const silent=String(answer||"").trim().toUpperCase()==="SILENT"||String(answer||"").trim().toUpperCase().startsWith("SILENT\n");if(!silent)AstraReply(answer);return{configured:true,data,answer,silent,vision:!!image,tradingContext,coachState:ASTRA.modules.coach?.snapshot?.()};}
        catch(error){console.error("ASTRA AI API:",error);if(!extra.proactive)AstraReply("I hit a connection problem. Try that again.");return{configured:true,error:error.message};}
    }
};
ASTRA.registerModule("ai",AIGateway);console.log("ASTRA AI Gateway v3.1 Loaded");
