/* =========================================
   ASTRA AI GATEWAY v3.6
   Natural trading mentor + assistant + research + top-down checkpoints + persistent history
========================================= */
const AIGateway={
    extractAnswer(data){if(typeof data==="string")return data;if(data?.answer)return data.answer;if(data?.message)return data.message;const response=data?.response||data;if(typeof response==="string")return response;if(response?.output_text)return response.output_text;const output=response?.output;if(Array.isArray(output)){const text=output.flatMap(item=>Array.isArray(item?.content)?item.content:[]).filter(item=>item?.type==="output_text"&&typeof item?.text==="string").map(item=>item.text).join("\n");if(text)return text;}return JSON.stringify(data);},
    getTradingSystem(){const t=ASTRA.modules.trading?.strategy;if(!t)return null;return JSON.parse(JSON.stringify(t));},
    isTradingContext(message,extra={}){const text=String(message||"").toLowerCase();return !!(extra.trading||extra.analysis||extra.backtest||extra.liveTrading||extra.proactive||/\b(trad|trade|trading|chart|market|setup|entry|exit|liquidity|supply|demand|structure|timeframe|backtest|forex|pair|position|stop|target|risk|markup|mark up|marked|mistake|performance|gbpusd|gbp\/usd|eurusd|eur\/usd|xauusd|nas100)\b/.test(text));},
    syncNaturalState(message){const coach=ASTRA.modules.coach;if(!coach)return null;const text=String(message||"");const lower=text.toLowerCase();const pair=(text.match(/\b(?:GBP\s*\/\s*USD|EUR\s*\/\s*USD|USD\s*\/\s*JPY|AUD\s*\/\s*USD|USD\s*\/\s*CAD|USD\s*\/\s*CHF|NZD\s*\/\s*USD|XAU\s*\/\s*USD|NAS100|US30|SPX500|[A-Z]{6})\b/i)||[])[0];const tf=(text.match(/\b(?:1m|3m|5m|15m|30m|1h|2h|4h|6h|8h|12h|1d|1w|monthly|weekly|daily|hourly)\b/i)||[])[0];const info={};if(pair)info.pair=pair.replace(/\s+/g,"").toUpperCase();if(tf)info.timeframe=tf.toUpperCase();if(Object.keys(info).length)coach.setMarket(info);if(/\b(backtest|back testing|testing the setup)\b/i.test(lower))coach.setState("BACKTEST");else if(/\b(live trade|live trading|about to enter|in the trade)\b/i.test(lower))coach.setState("LIVE_TRADING");else if(/\b(plan|planning)\b/i.test(lower))coach.setState("PLANNING");else if(/\b(review|reviewing)\b/i.test(lower))coach.setState("REVIEW");else if(/\b(journal|journaling)\b/i.test(lower))coach.setState("JOURNAL");else if(/\b(marking up|markup|mark up|chart)\b/i.test(lower))coach.setState("MARKUP");const marked=text.match(/\b(?:mark(?:ed)?|marking)\s+(?:the\s+)?(?:liquidity|supply|demand|zone|high|low|level)[^.!?]*/i);if(marked)coach.addMarked(marked[0]);return coach.snapshot();},
    async ask(userMessage,extra={}){
        const topDown=ASTRA.modules.topDownCoach;
        if(!extra.skipTopDown&&topDown){
            const checkpoint=await topDown.handle(userMessage);
            if(checkpoint?.handled){
                if(checkpoint.message&&!extra.proactive)AstraReply(checkpoint.message);
                else if(checkpoint.feedback&&!extra.proactive)AstraReply(checkpoint.feedback);
                else if(checkpoint.blocked&&!extra.proactive)AstraReply(checkpoint.message||"I need the shared chart before I can inspect this timeframe.");
                return checkpoint;
            }
        }
        const research=ASTRA.modules.research;
        if(!extra.skipResearch&&research?.isResearchRequest?.(userMessage))return research.ask(userMessage,{silent:!!extra.proactive});
        const tradingContext=this.isTradingContext(userMessage,extra);this.syncNaturalState(userMessage);
        const base=ASTRA.modules.context?.build?.()||{};const coach=ASTRA.modules.coach?.buildContext?.()||ASTRA.modules.coach?.context?.()||{};const mentor=ASTRA.modules.coach?.mentorContext?.()||{};
        const context=Object.assign({},base,coach,extra.context||{},{astraResponseStyle:{role:"70% trading coach, 30% assistant",persona:"a calm, experienced trading mentor sitting beside Jay",tone:"natural, warm, direct, conversational",priority:"answer the actual question first, then coach when useful",vocabulary:"plain everyday words; use trading terms when they are part of Jay's system",length:"usually 1-4 short sentences; expand only when the situation needs teaching",coaching:"watch the process; notice mistakes, skipped steps, weak reasoning, emotional decisions, and rule breaks; point them out clearly but briefly; give one useful next step",mentor:"talk like a real mentor beside the trader, not like a report or customer-support bot; remember what was just discussed and refer to it naturally",challenge:"do not automatically agree with Jay; respectfully challenge a setup when the visible evidence or his plan disagrees",topDown:"for chart work, think higher timeframe first, then lower timeframe, liquidity, structure, confirmation, and execution",backtesting:"treat backtesting as practice with a mentor; keep it separate from live performance; when Jay makes a rule-breaking test decision, point it out immediately, explain why in one short thought, and let him continue",proactive:"when screen or market evidence is available, speak only when something meaningful changed or Jay may be missing an important rule break",silence:"if there is nothing useful to add, do not manufacture commentary",avoid:"long introductions, repeated disclaimers, formal sections, filler, repeating the same correction, pretending to see details that are not visible",answerQuestionDirectly:true},mentorState:mentor});
        const history=ASTRA.modules.history;
        if(history){context.astraHistory=history.contextForAI(40);context.historyInstruction="ASTRA has persistent history. Use it to recognize recurring mistakes, previous lessons, prior setups, and what Jay was doing before. Warn him when the current situation resembles a documented mistake, but only when the evidence supports the comparison. Never invent history.";}
        if(tradingContext){const memory=ASTRA.modules.memory;const session=memory?.recordMarketMessage?.(userMessage,extra);context.currentMarketSession=session||memory?.currentMarketSession?.()||null;context.marketMemoryInstruction="Remember the current market session. If Jay asks where we were, identify the saved pair, timeframe, markup, plan, last screen analysis, and last message. Never invent missing details.";context.tradingSystem={loaded:true,source:"ASTRA.modules.trading.strategy",instruction:"This is Jay's source of truth for trading. Use it when coaching. Never replace it with a generic strategy. Keep live trading and backtesting separate.",system:this.getTradingSystem()};context.coachInstruction="Coach first, assist second. If Jay skips a key step in his own system, point it out without lecturing. If the screen shows a meaningful conflict with his plan, speak up. If there is no meaningful issue, stay quiet.";context.topDownInstruction="For markup and backtesting, evaluate higher-timeframe objective and context before lower-timeframe execution. Consider supply/demand, liquidity, structure shift, confirmation, and risk before calling a setup aligned.";}
        let image=extra.image||null;let vision=!!extra.vision;if(!image&&ASTRA.modules.screen?.sharing&&ASTRA.modules.screen?.getFrame){image=ASTRA.modules.screen.getFrame({maxWidth:1280,quality:0.55});if(image){vision=true;context.screenContext={shared:true,frameAttached:true,instruction:"Inspect the attached current screen directly. Only describe what is actually visible. If chart details are unclear, say what is unclear rather than guessing."};}}
        const payload={question:userMessage,context};if(image)payload.image=image;if(vision)payload.vision=true;const api=ASTRA.modules.api;if(!api?.status?.().configured){if(!extra.proactive&&!extra.returnOnly)AstraReply("AI Gateway ready. Configure ASTRA.modules.api first.");return{configured:false,payload};}
        try{const data=await api.request("",{method:"POST",body:JSON.stringify(payload)});const answer=this.extractAnswer(data);const silent=String(answer||"").trim().toUpperCase()==="SILENT"||String(answer||"").trim().toUpperCase().startsWith("SILENT\n");if(!silent&&!extra.returnOnly){if(!extra.proactive||ASTRA.modules.coach?.recordCoachSpeech?.(answer)!==false)AstraReply(answer);}return{configured:true,data,answer,silent,vision:!!image,tradingContext,coachState:ASTRA.modules.coach?.snapshot?.()};}
        catch(error){console.error("ASTRA AI API:",error);if(!extra.proactive&&!extra.returnOnly)AstraReply("I hit a connection problem. Try that again.");return{configured:true,error:error.message};}
    }
};
ASTRA.registerModule("ai",AIGateway);console.log("ASTRA AI Gateway v3.6 Loaded — full canonical trading strategy injected");
