/* =========================================
   ASTRA COACH ENGINE v1.4
   70% coach / 30% assistant
   Natural mentor behavior + persistent trading context
========================================= */
const CoachEngine=(()=>{
const KEY="ASTRA_COACH_STATE";const DEFAULT={state:"MARKUP",pair:null,timeframe:null,session:null,objective:null,markedUp:[],plan:null,lastObservation:null,lastDecision:null,observations:[],lessons:[],mistakes:[],strengths:[],setupHistory:[],lastCoachSpeech:null,updatedAt:null};let data=load();let observerTimer=null;let observerBusy=false;
function load(){try{return{...DEFAULT,...(JSON.parse(localStorage.getItem(KEY))||{})};}catch{return{...DEFAULT};}}function save(){data.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(data));}
function normalizeState(value){const text=String(value||"").toUpperCase();const map={MARKUP:"MARKUP",MARKING:"MARKUP",BACKTEST:"BACKTEST",BACKTESTING:"BACKTEST",PLAN:"PLANNING",PLANNING:"PLANNING",LIVE:"LIVE_TRADING",TRADING:"LIVE_TRADING",LIVE_TRADING:"LIVE_TRADING",REVIEW:"REVIEW",REVIEWING:"REVIEW",JOURNAL:"JOURNAL",JOURNALING:"JOURNAL"};return map[text]||"MARKUP";}
function setState(state,reason=""){data.state=normalizeState(state);if(reason)data.lastDecision=typeof reason==="string"?reason:JSON.stringify(reason);save();return snapshot();}
function syncState(){const mode=localStorage.getItem("ASTRA_CURRENT_MODE")||localStorage.getItem("ASTRA_MODE");if(mode&&["BACKTEST","BUILD","VISION","VOICE","TRADING"].includes(String(mode).toUpperCase()))data.state=normalizeState(mode);return data.state;}
function setMarket(info={}){if(info.pair!==undefined)data.pair=info.pair||null;if(info.timeframe!==undefined)data.timeframe=info.timeframe||null;if(info.session!==undefined)data.session=info.session||null;if(info.objective!==undefined)data.objective=info.objective||null;if(info.plan!==undefined)data.plan=info.plan||null;if(Array.isArray(info.markedUp))data.markedUp=info.markedUp.slice();save();return snapshot();}
function addMarked(item){const value=String(item||"").trim();if(value&&!data.markedUp.includes(value))data.markedUp.push(value);save();return snapshot();}
function addObservation(observation){if(!observation)return snapshot();const entry=typeof observation==="string"?{message:observation,date:new Date().toISOString()}:{...observation,date:observation.date||new Date().toISOString()};data.lastObservation=entry;data.observations.push(entry);if(data.observations.length>50)data.observations=data.observations.slice(-50);save();return snapshot();}
function addLesson(x){const v=String(x||"").trim();if(v){data.lessons.push({text:v,date:new Date().toISOString()});save();}return snapshot();}
function addMistake(x){const v=String(x||"").trim();if(v){data.mistakes.push({text:v,date:new Date().toISOString()});save();}return snapshot();}
function addStrength(x){const v=String(x||"").trim();if(v){data.strengths.push({text:v,date:new Date().toISOString()});save();}return snapshot();}
function tradingSystem(){const s=ASTRA.modules.trading?.strategy;return s?{name:ASTRA.modules.trading.name,philosophy:s.philosophy||[],framework:s.framework||{},rules:s.rules||[]}:null;}
function journal(){return ASTRA.modules.journal?.getData?.()||{trades:[]};}
function backtest(){return ASTRA.modules.backtesting?.getTrades?.()||[];}
function setupValidation(setup={}){const system=tradingSystem();if(!system)return{status:"UNKNOWN",reasons:["Trading system is not loaded."]};const reasons=[];let score=0;const checks=[setup.higherTimeframeContext||setup.higherTF||data.objective,setup.structureShift||setup.shift,setup.liquidity,setup.confirmation];if(checks[0])score++;else reasons.push("Higher-timeframe context is missing.");if(checks[1])score++;else reasons.push("No clear lower-timeframe structure shift yet.");if(checks[2])score++;else reasons.push("Liquidity is not clearly identified.");if(checks[3])score++;else reasons.push("Entry confirmation is missing.");const status=score===4?"ALIGNED":score>=2?"PARTIALLY ALIGNED":"NOT ALIGNED";const result={status,score,checks:4,reasons,system:"Jay Fractal Market Delivery System"};data.setupHistory.push({date:new Date().toISOString(),setup,result});save();return result;}
function riskGuardrail(trade={}){const warnings=[];if(!trade.higherTimeframeContext)warnings.push("No higher-timeframe context.");if(!trade.structureShift)warnings.push("No clear structure shift.");if(!trade.liquidity)warnings.push("Liquidity is not confirmed.");if(!trade.confirmation)warnings.push("Entry confirmation is missing.");if(trade.ruleBreak)warnings.push("This may repeat a known rule break.");return{blocked:warnings.length>=3,warnings,rules:tradingSystem()?.rules||[],tradeCount:journal().trades?.length||0};}
function mistakePatterns(){const counts={};(journal().trades||[]).forEach(t=>{const raw=t.mistakes||t.mistake||t.ruleBreak||"";String(raw).split(/[,;|]/).map(x=>x.trim().toLowerCase()).filter(Boolean).forEach(x=>counts[x]=(counts[x]||0)+1);});data.mistakes.forEach(m=>{const k=m.text.toLowerCase();counts[k]=(counts[k]||0)+1;});return Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([mistake,count])=>({mistake,count}));}
function performanceInsight(){const trades=journal().trades||[];const total=trades.length;const wins=trades.filter(t=>String(t.result).toLowerCase()==="win").length;const losses=trades.filter(t=>String(t.result).toLowerCase()==="loss").length;const setups={};trades.forEach(t=>{const s=t.setup||"Unknown";setups[s]??={trades:0,wins:0};setups[s].trades++;if(String(t.result).toLowerCase()==="win")setups[s].wins++;});const ranked=Object.entries(setups).map(([name,v])=>({name,...v,winRate:v.trades?Math.round(v.wins/v.trades*100):0})).sort((a,b)=>b.winRate-a.winRate);return{total,wins,losses,winRate:total?Math.round(wins/total*100):0,bestSetup:ranked[0]||null,setupStats:ranked,topMistakes:mistakePatterns().slice(0,5),lessons:data.lessons.slice(-10)};}
function backtestInsight(){const trades=backtest();if(!trades.length)return{total:0,message:"No backtest trades recorded yet."};const wins=trades.filter(t=>Number(t.pnl)>0).length;const losses=trades.filter(t=>Number(t.pnl)<0).length;return{total:trades.length,wins,losses,winRate:Math.round(wins/trades.length*100),netPnl:trades.reduce((s,t)=>s+Number(t.pnl||0),0)};}
function screenObservation(){const screen=ASTRA.modules.screen;if(!screen)return null;const analysis=screen.getAnalysis?.();if(analysis)addObservation(analysis);return analysis||data.lastObservation||null;}
function snapshot(){syncState();return JSON.parse(JSON.stringify({state:data.state,pair:data.pair,timeframe:data.timeframe,session:data.session,objective:data.objective,markedUp:data.markedUp,plan:data.plan,lastObservation:data.lastObservation,observations:data.observations.slice(-20),lastDecision:data.lastDecision,lessons:data.lessons.slice(-10),mistakes:data.mistakes.slice(-10),strengths:data.strengths.slice(-10),setupHistory:data.setupHistory.slice(-10),lastCoachSpeech:data.lastCoachSpeech,updatedAt:data.updatedAt}));}
function mentorContext(){const s=snapshot();const system=tradingSystem();const observation=s.lastObservation||{};const rules=system?.rules||[];return{role:"trading mentor sitting beside Jay",state:s.state,pair:s.pair,timeframe:s.timeframe,objective:s.objective,markedUp:s.markedUp,plan:s.plan,lastObservation:observation,recentMistakes:s.mistakes.slice(-5),recentLessons:s.lessons.slice(-5),tradingRules:rules,backtestMode:s.state==="BACKTEST",instruction:"Watch the process, not just the answer. If Jay skips a required step or breaks his trading plan, point it out briefly and immediately. Do not lecture or repeat the same correction. Ask one useful next question when needed. During backtesting, treat every setup as a lesson and keep it completely separate from live-trading performance."};}
function recordCoachSpeech(text){const value=String(text||"").trim();if(!value)return false;const normalized=value.toLowerCase().replace(/\s+/g," ");if(normalized&&normalized===String(data.lastCoachSpeech||"").toLowerCase().replace(/\s+/g," "))return false;data.lastCoachSpeech=value;save();return true;}
async function mentorCheck(input="",extra={}){const state=snapshot();const validation=setupValidation(extra.setup||{});return{state,validation,mentor:mentorContext(),input:String(input||"")};}
async function observe(){if(observerBusy||!['MARKUP','BACKTEST','REVIEW'].includes(syncState())||!ASTRA.modules.screen?.sharing)return null;observerBusy=true;try{const frame=ASTRA.modules.screen.getFrame?.({maxWidth:1280,quality:0.5});if(!frame)return null;const analysis=ASTRA.modules.screen.getAnalysis?.()||{};addObservation({capturedAt:new Date().toISOString(),frameAttached:true,...analysis});const mode=data.state;const ai=ASTRA.modules.ai;if(ai?.ask){const prompt=mode==="BACKTEST"?"Watch this backtest chart like a calm trading mentor sitting beside Jay. Compare what is visible with his Jay Fractal Market Delivery System. If he is skipping top-down context, structure, liquidity, confirmation, or forcing a setup, point it out briefly. If there is nothing important to correct, reply exactly SILENT. Do not repeat the last coaching point.":"Watch the current chart like a calm trading mentor sitting beside Jay. Compare what is visible with his trading system. Only speak if you notice something important, a likely rule break, or a meaningful next step. If nothing important changed, reply exactly SILENT. Do not repeat the last coaching point.";const result=await ai.ask(prompt,{image:frame,vision:true,trading:true,proactive:true,backtest:mode==="BACKTEST",context:{coachObservation:true,currentState:snapshot(),mentor:mentorContext(),lastCoachSpeech:data.lastCoachSpeech}});if(result?.answer&&!result.silent)recordCoachSpeech(result.answer);return result;}return frame;}catch(error){console.warn("ASTRA coach observer:",error);return null;}finally{observerBusy=false;}}
function startObserver(intervalMs=12000){stopObserver();observerTimer=setInterval(observe,Math.max(10000,Number(intervalMs)||12000));observe();return true;}
function stopObserver(){if(observerTimer){clearInterval(observerTimer);observerTimer=null;}return true;}
function status(){return{online:true,state:syncState(),pair:data.pair,timeframe:data.timeframe,markedUp:data.markedUp.length,observing:!!observerTimer,screenSharing:!!ASTRA.modules.screen?.sharing};}
ASTRA.commands.push({trigger:"coach status",action:()=>AstraReply(JSON.stringify(status()))});ASTRA.commands.push({trigger:"where were we",action:()=>{const s=snapshot();AstraReply(`${s.pair||"No pair saved yet."}${s.timeframe?" • "+s.timeframe:""}. ${s.markedUp.length?"Marked: "+s.markedUp.join(", "):"Nothing marked yet."}${s.lastDecision?" Last decision: "+s.lastDecision:""}`);}});ASTRA.commands.push({trigger:"what did we mark",action:()=>{const s=snapshot();AstraReply(s.markedUp.length?`We marked: ${s.markedUp.join(", ")}.`:"We haven't saved any marked levels yet.");}});ASTRA.commands.push({trigger:"setup check",action:()=>AstraReply(JSON.stringify(setupValidation({higherTimeframeContext:data.objective,liquidity:data.markedUp.find(x=>/liquidity/i.test(x)),structureShift:data.lastObservation?.structure,confirmation:data.plan}))) });ASTRA.commands.push({trigger:"performance insight",action:()=>AstraReply(JSON.stringify(performanceInsight()))});ASTRA.commands.push({trigger:"backtest insight",action:()=>AstraReply(JSON.stringify(backtestInsight()))});ASTRA.commands.push({trigger:"start coach watch",action:()=>{startObserver();AstraReply("Coach watch is on.");}});ASTRA.commands.push({trigger:"stop coach watch",action:()=>{stopObserver();AstraReply("Coach watch is off.");}});
return{name:"ASTRA Coach Engine",version:"1.4",setState,setMarket,addMarked,addObservation,addLesson,addMistake,addStrength,tradingSystem,setupValidation,riskGuardrail,mistakePatterns,performanceInsight,backtestInsight,screenObservation,mentorContext,mentorCheck,recordCoachSpeech,startObserver,stopObserver,status,snapshot,context:()=>({coachEngine:{loaded:true,state:snapshot(),tradingSystem:tradingSystem(),performance:performanceInsight(),backtest:backtestInsight(),mistakePatterns:mistakePatterns().slice(0,5),screen:screenObservation(),mentor:mentorContext()}}),buildContext:()=>({coachEngine:{loaded:true,state:snapshot(),tradingSystem:tradingSystem(),performance:performanceInsight(),backtest:backtestInsight(),mistakePatterns:mistakePatterns().slice(0,5),screen:screenObservation(),mentor:mentorContext()}})};})();
ASTRA.modules.coach=CoachEngine;ASTRA.modules.coachEngine=CoachEngine;console.log("ASTRA Coach Engine v1.4 Loaded");
