/* =========================================
   ASTRA COACH ENGINE v1.2
   70% coach / 30% assistant
========================================= */
const CoachEngine=(()=>{
const KEY="ASTRA_COACH_STATE";const DEFAULT={state:"MARKUP",pair:null,timeframe:null,session:null,objective:null,markedUp:[],plan:null,lastObservation:null,lastDecision:null,lessons:[],mistakes:[],strengths:[],setupHistory:[],updatedAt:null};let data=load();let observerTimer=null;let observerBusy=false;
function load(){try{return{...DEFAULT,...(JSON.parse(localStorage.getItem(KEY))||{})};}catch{return{...DEFAULT};}}function save(){data.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(data));}
function normalizeState(value){const text=String(value||"").toUpperCase();const map={MARKUP:"MARKUP",MARKING:"MARKUP",BACKTEST:"BACKTEST",BACKTESTING:"BACKTEST",PLAN:"PLANNING",PLANNING:"PLANNING",LIVE:"LIVE_TRADING",TRADING:"LIVE_TRADING",LIVE_TRADING:"LIVE_TRADING",REVIEW:"REVIEW",REVIEWING:"REVIEW",JOURNAL:"JOURNAL",JOURNALING:"JOURNAL"};return map[text]||"MARKUP";}
function setState(state,reason=""){data.state=normalizeState(state);if(reason)data.lastDecision=reason;save();return snapshot();}function syncState(){const mode=localStorage.getItem("ASTRA_CURRENT_MODE");if(mode&&["BACKTEST","BUILD","VISION","VOICE","TRADING"].includes(mode))data.state=normalizeState(mode);return data.state;}
function setMarket(info={}){if(info.pair!==undefined)data.pair=info.pair||null;if(info.timeframe!==undefined)data.timeframe=info.timeframe||null;if(info.session!==undefined)data.session=info.session||null;if(info.objective!==undefined)data.objective=info.objective||null;if(info.plan!==undefined)data.plan=info.plan||null;if(Array.isArray(info.markedUp))data.markedUp=info.markedUp.slice();save();return snapshot();}
function addMarked(item){const value=String(item||"").trim();if(value&&!data.markedUp.includes(value))data.markedUp.push(value);save();return snapshot();}function addLesson(x){const v=String(x||"").trim();if(v){data.lessons.push({text:v,date:new Date().toISOString()});save();}return snapshot();}function addMistake(x){const v=String(x||"").trim();if(v){data.mistakes.push({text:v,date:new Date().toISOString()});save();}return snapshot();}function addStrength(x){const v=String(x||"").trim();if(v){data.strengths.push({text:v,date:new Date().toISOString()});save();}return snapshot();}
function tradingSystem(){const s=ASTRA.modules.trading?.strategy;return s?{philosophy:s.philosophy||[],framework:s.framework||{},rules:s.rules||[]}:null;}function journal(){return ASTRA.modules.journal?.getData?.()||{trades:[]};}function backtest(){return ASTRA.modules.backtesting?.getTrades?.()||[];}
function setupValidation(setup={}){const system=tradingSystem();if(!system)return{status:"UNKNOWN",reasons:["Trading system is not loaded."]};const reasons=[];let score=0;const checks=[setup.higherTimeframeContext||setup.higherTF||data.objective,setup.structureShift||setup.shift,setup.liquidity,setup.confirmation];if(checks[0])score++;else reasons.push("Higher-timeframe context is missing.");if(checks[1])score++;else reasons.push("No clear lower-timeframe structure shift yet.");if(checks[2])score++;else reasons.push("Liquidity is not clearly identified.");if(checks[3])score++;else reasons.push("Entry confirmation is missing.");const status=score===4?"ALIGNED":score>=2?"PARTIALLY ALIGNED":"NOT ALIGNED";const result={status,score,checks:4,reasons,system:"Jay Fractal Market Delivery System"};data.setupHistory.push({date:new Date().toISOString(),setup,result});save();return result;}
function riskGuardrail(trade={}){const warnings=[];if(!trade.higherTimeframeContext)warnings.push("No higher-timeframe context.");if(!trade.structureShift)warnings.push("No clear structure shift.");if(!trade.liquidity)warnings.push("Liquidity is not confirmed.");if(!trade.confirmation)warnings.push("Entry confirmation is missing.");if(trade.ruleBreak)warnings.push("This may repeat a known rule break.");return{blocked:warnings.length>=3,warnings,rules:tradingSystem()?.rules||[],tradeCount:journal().trades?.length||0};}
function mistakePatterns(){const counts={};(journal().trades||[]).forEach(t=>{const raw=t.mistakes||t.mistake||t.ruleBreak||"";String(raw).split(/[,;|]/).map(x=>x.trim().toLowerCase()).filter(Boolean).forEach(x=>counts[x]=(counts[x]||0)+1);});data.mistakes.forEach(m=>{const k=m.text.toLowerCase();counts[k]=(counts[k]||0)+1;});return Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([mistake,count])=>({mistake,count}));}
function performanceInsight(){const trades=journal().trades||[];const total=trades.length;const wins=trades.filter(t=>String(t.result).toLowerCase()==="win").length;const losses=trades.filter(t=>String(t.result).toLowerCase()==="loss").length;const setups={};trades.forEach(t=>{const s=t.setup||"Unknown";setups[s]??={trades:0,wins:0};setups[s].trades++;if(String(t.result).toLowerCase()==="win")setups[s].wins++;});const ranked=Object.entries(setups).map(([name,v])=>({name,...v,winRate:v.trades?Math.round(v.wins/v.trades*100):0})).sort((a,b)=>b.winRate-a.winRate);return{total,wins,losses,winRate:total?Math.round(wins/total*100):0,bestSetup:ranked[0]||null,setupStats:ranked,topMistakes:mistakePatterns().slice(0,5),lessons:data.lessons.slice(-10)};}
function backtestInsight(){const trades=backtest();if(!trades.length)return{total:0,message:"No backtest trades recorded yet."};const wins=trades.filter(t=>Number(t.pnl)>0).length;const losses=trades.filter(t=>Number(t.pnl)<0).length;return{total:trades.length,wins,losses,winRate:Math.round(wins/trades.length*100),netPnl:trades.reduce((s,t)=>s+Number(t.pnl||0),0)};}
function screenObservation(){const screen=ASTRA.modules.screen;if(!screen)return null;const analysis=screen.getAnalysis?.();if(analysis){data.lastObservation=analysis;save();}return analysis||data.lastObservation||null;}
function snapshot(){syncState();return JSON.parse(JSON.stringify({state:data.state,pair:data.pair,timeframe:data.timeframe,session:data.session,objective:data.objective,markedUp:data.markedUp,plan:data.plan,lastObservation:data.lastObservation,lastDecision:data.lastDecision,lessons:data.lessons.slice(-10),mistakes:data.mistakes.slice(-10),strengths:data.strengths.slice(-10),updatedAt:data.updatedAt}));}
function context(){return{coachEngine:{loaded:true,state:snapshot(),tradingSystem:tradingSystem(),performance:performanceInsight(),backtest:backtestInsight(),mistakePatterns:mistakePatterns().slice(0,5),screen:screenObservation()}};}function buildContext(){return context();}
async function observe(){if(observerBusy||data.state!=="MARKUP"||!ASTRA.modules.screen?.sharing)return null;observerBusy=true;try{const frame=ASTRA.modules.screen.getFrame?.({maxWidth:1280,quality:0.5});if(!frame)return null;data.lastObservation={capturedAt:new Date().toISOString(),frameAttached:true,...(ASTRA.modules.screen.getAnalysis?.()||{})};save();const ai=ASTRA.modules.ai;if(ai?.ask){return await ai.ask("Look at the current shared chart. Only speak if you notice something important that Jay may be missing or that conflicts with his trading system. Keep it to 1-2 short natural sentences. If there is nothing important, reply exactly SILENT.",{image:frame,vision:true,trading:true,proactive:true,context:{coachObservation:true,currentState:snapshot()}});}return frame;}catch(error){console.warn("ASTRA coach observer:",error);return null;}finally{observerBusy=false;}}
function startObserver(intervalMs=15000){stopObserver();observerTimer=setInterval(observe,Math.max(10000,Number(intervalMs)||15000));observe();return true;}function stopObserver(){if(observerTimer){clearInterval(observerTimer);observerTimer=null;}return true;}function status(){return{online:true,state:syncState(),pair:data.pair,timeframe:data.timeframe,markedUp:data.markedUp.length,observing:!!observerTimer,screenSharing:!!ASTRA.modules.screen?.sharing};}
ASTRA.commands.push({trigger:"coach status",action:()=>AstraReply(JSON.stringify(status()))});ASTRA.commands.push({trigger:"where were we",action:()=>{const s=snapshot();AstraReply(`${s.pair||"No pair saved yet."}${s.timeframe?" • "+s.timeframe:""}. ${s.markedUp.length?"Marked: "+s.markedUp.join(", "):"Nothing marked yet."}${s.lastDecision?" Last decision: "+s.lastDecision:""}`);}});ASTRA.commands.push({trigger:"what did we mark",action:()=>{const s=snapshot();AstraReply(s.markedUp.length?`We marked: ${s.markedUp.join(", ")}.`:"We haven't saved any marked levels yet.");}});ASTRA.commands.push({trigger:"setup check",action:()=>AstraReply(JSON.stringify(setupValidation({higherTimeframeContext:data.objective,liquidity:data.markedUp.find(x=>/liquidity/i.test(x)),structureShift:data.lastObservation?.structure,confirmation:data.plan}))) });ASTRA.commands.push({trigger:"performance insight",action:()=>AstraReply(JSON.stringify(performanceInsight()))});ASTRA.commands.push({trigger:"backtest insight",action:()=>AstraReply(JSON.stringify(backtestInsight()))});ASTRA.commands.push({trigger:"start coach watch",action:()=>{startObserver();AstraReply("Coach watch is on.");}});ASTRA.commands.push({trigger:"stop coach watch",action:()=>{stopObserver();AstraReply("Coach watch is off.");}});
return{name:"ASTRA Coach Engine",version:"1.2",setState,setMarket,addMarked,addLesson,addMistake,addStrength,tradingSystem,setupValidation,riskGuardrail,mistakePatterns,performanceInsight,backtestInsight,screenObservation,startObserver,stopObserver,status,snapshot,context,buildContext};})();
ASTRA.modules.coach=CoachEngine;ASTRA.modules.coachEngine=CoachEngine;console.log("ASTRA Coach Engine v1.2 Loaded");
