/* =========================================
   VEGA TOP-DOWN COACH v3.3
   Phase 2 trading workflow
   Deterministic timeframe-specific mentor review contracts.
========================================= */
const TopDownCoach=(()=>{
 const KEY="ASTRA_TOP_DOWN_SESSION";
 const DEFAULT={active:false,timeframes:["WEEKLY","DAILY","4H","1H","30M","15M","5M"],index:0,completed:[],awaitingReview:false,currentTranscript:"",lastAnalysis:"",lastReview:null,updatedAt:null};
 let stored={};try{stored=JSON.parse(localStorage.getItem(KEY)||"{}")}catch{}
 let state={...DEFAULT,...stored,active:false,awaitingReview:false};
 let voiceGuardInstalled=false,allowAnnouncement=false;
 const save=()=>{state.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state))};
 const current=()=>state.timeframes[state.index]||null;
 const snapshot=()=>JSON.parse(JSON.stringify({...state,currentTimeframe:current()}));
 const normalize=t=>String(t||"").trim().toUpperCase();
 const roleFor=tf=>({WEEKLY:"direction and bigger market context only — do not treat this as an execution timeframe",DAILY:"direction and bigger market context — refine the Weekly map with agreement or disagreement","4H":"main trading narrative — explain where price is coming from, where it may deliver, important areas and scenarios","1H":"fractal opportunities inside the 4H narrative","30M":"fractal opportunities and lower-timeframe delivery inside the larger narrative","15M":"confirmation timeframe — evaluate the required structure shift, liquidity context and momentum","5M":"entry refinement and/or direct confirmation after the larger narrative is aligned"}[tf]||"analysis");
 const requirementsFor=tf=>({WEEKLY:["context/direction","recent significant leg","Weekly trading range","important supply and demand areas","liquidity assessment","narrative/delivery","if-this-then-that scenarios","opportunity path into lower timeframes","invalidation"],DAILY:["Weekly context agreement or disagreement","Daily structure/context","important supply and demand areas","liquidity assessment","refined narrative/delivery","if-this-then-that scenarios","Daily/4H opportunity path","invalidation"],"4H":["4H structure","main narrative/delivery","important supply and demand areas","liquidity assessment","scenarios","opportunity path into 1H/30M","invalidation"],"1H":["1H structure","delivery inside the 4H narrative","relevant supply and demand/POI","liquidity assessment","fractal opportunity","invalidation"],"30M":["30M structure","lower-timeframe delivery","relevant supply and demand/POI","liquidity assessment","fractal opportunity","invalidation"],"15M":["15M structure","liquidity context","required structure shift/confirmation","momentum or displacement where relevant","confirmation decision","invalidation"],"5M":["5M entry refinement/direct confirmation","liquidity context where relevant","required structure shift/confirmation","momentum/displacement where relevant","invalidation"]}[tf]||["structure","narrative/delivery","supply and demand","liquidity","opportunity","invalidation"]);
 function promptFor(tf){return `Start with the ${tf} chart. Your job here is ${roleFor(tf)}. Cover the ${requirementsFor(tf).join(", ")}. Take your time. I will stay quiet until you say you're finished.`;}
 function isTopDownStart(text){const t=String(text||"").toLowerCase().replace(/[.,!?]/g," ").replace(/\s+/g," ").trim();return /\btop\s*-?\s*down(?:\s+(?:analysis|analyses|analyzing))?\b/.test(t)&&(/\b(?:i'?m|im|i am|we'?re|we are|let'?s|lets|i'?ll|ill|i will|we will|going to|gonna|want to|ready to|start|begin|do|doing|analy[sz]e|about to)\b/.test(t)||/^(?:astra\s*,?\s*)?(?:top\s*-?\s*down)/.test(t));}
 function isFinished(text){const t=String(text||"").trim();return /\b(?:i'?m|im|i am|we'?re|we are)\s+(?:finished|done)\b|\b(?:i'?m|im|i am)\s+(?:all\s+)?finished\b|\bfinished(?:\s+with)?(?:\s+(?:the\s+)?)?(?:weekly|daily|4h|1h|30m|15m|5m|analysis|analyzing)?\b|\b(?:that'?s|thats)\s+(?:it|all)\b|\b(?:analysis|analyzing)\s+(?:is\s+)?(?:finished|done|complete)\b/i.test(t);}
 function installVoiceGuard(){if(voiceGuardInstalled)return;const voice=ASTRA.modules.voice;if(!voice?.speak)return;const original=voice.speak.bind(voice);voice.speak=function(text,...args){if(state.active&&!state.awaitingReview&&!allowAnnouncement)return false;return original(text,...args);};voiceGuardInstalled=true;}
 function withAnnouncement(fn){allowAnnouncement=true;try{return fn();}finally{setTimeout(()=>{allowAnnouncement=false;},2500);}}
 function start(timeframes){installVoiceGuard();ASTRA.modules.voice?.stopSpeaking?.({ignoreMs:1500});if(Array.isArray(timeframes)&&timeframes.length)state.timeframes=timeframes.map(normalize).filter(Boolean);state.active=true;state.index=0;state.completed=[];state.awaitingReview=false;state.currentTranscript="";state.lastAnalysis="";state.lastReview=null;ASTRA.modules.coach?.stopObserver?.();save();return withAnnouncement(()=>({handled:true,started:true,message:`Okay, we're ready. ${promptFor(current())}`,state:snapshot()}));}
 function appendAnalysis(text){const v=String(text||"").trim();if(v){state.currentTranscript=[state.currentTranscript,v].filter(Boolean).join("\n");save();}}
 function buildReviewPrompt(tf,analysis,system){const req=requirementsFor(tf);return `You are VEGA, acting as Jay's top-down trading mentor. Review ONLY the current ${tf} timeframe analysis against Jay's original Trading Strategy and the timeframe-specific contract below. TIMEFRAME ROLE: ${roleFor(tf)}. REQUIRED ${tf} CONTRACT: ${req.map((x,i)=>`${i+1}) ${x}`).join("; ")}. JAY'S SPOKEN ANALYSIS: ${analysis||"(No explanation captured.)"}. Inspect the shared chart and compare what Jay said with what is visible, but do not invent details you cannot see.\n\nMENTOR RULES: Track both what Jay covered and what he did not cover. Missing means Jay did not address a required contract item. NEVER import requirements from another timeframe. A liquidity statement such as 'I don't see EQH/EQL/trendline liquidity' is a valid liquidity assessment unless the visible chart clearly contradicts it. A clear invalidation condition satisfies invalidation unless the current contract explicitly requires a numeric level. Do not require zone freshness, numeric levels, HH/HL/BOS labels, execution mechanics, risk details, or later-timeframe items unless explicitly listed in the current contract. If the chart contradicts something Jay stated, identify that contradiction specifically. Return missing items ONLY from the REQUIRED contract. Do not turn recommendations into missing items. Keep feedback concise. Return JSON only in this exact shape: {"status":"CORRECT"|"CORRECTION"|"UNCLEAR","correctPoints":[...],"incorrectPoints":[...],"missingPoints":[...],"missingLiquidity":[...],"feedback":"short spoken feedback","reason":"brief reason"}. Trading strategy context: ${JSON.stringify(system)}`;}
 function normalizeReview(raw){let parsed;try{parsed=JSON.parse(String(raw||"").trim().replace(/^```json\s*/i,"").replace(/\s*```$/,""))}catch{parsed={status:"UNCLEAR",correctPoints:[],incorrectPoints:[],missingPoints:[],missingLiquidity:[],feedback:String(raw||"").trim()||"I couldn't clearly verify that analysis yet.",reason:"Unstructured review."};}const allowed=["CORRECT","CORRECTION","UNCLEAR"];parsed.status=allowed.includes(String(parsed.status||"").toUpperCase())?String(parsed.status).toUpperCase():"UNCLEAR";for(const key of ["correctPoints","incorrectPoints","missingPoints","missingLiquidity"]){if(!Array.isArray(parsed[key]))parsed[key]=parsed[key]?[String(parsed[key])]:[];}parsed.feedback=String(parsed.feedback||"").trim()||"Let's review that carefully.";parsed.reason=String(parsed.reason||"").trim();return parsed;}
 function enforceContract(tf,review,analysis){
   const forbidden={WEEKLY:["zone freshness","fresh vs","freshness","numeric invalidation","numeric level","exact price","weekly close","hh/hl/bos","hh/hl","bos","15m","5m","entry plan","entry method","stop placement","stop loss","target levels","rr","risk plan","1%","daily/4h poi","daily and 4h poi","1h/30m"],DAILY:["15m","5m","entry plan","stop placement","stop loss","rr","risk plan"]};
   const clean=a=>(a||[]).filter(x=>!((forbidden[tf]||[]).some(w=>String(x).toLowerCase().includes(w))));
   review.missingPoints=clean(review.missingPoints);
   review.missingLiquidity=clean(review.missingLiquidity);
   const a=String(analysis||"").toLowerCase();
   const covered={
     "context/direction":/\b(bullish|bearish|direction|bias)\b/.test(a),
     "recent significant leg":/\b(recent|latest|current)\b[\s\w]{0,50}\b(leg|move|push|swing)\b/.test(a),
     "Weekly trading range":/\bweekly\b[\s\w]{0,30}\b(trading range|range)\b/.test(a),
     "important supply and demand areas":/\b(supply|demand)\b/.test(a),
     "liquidity assessment":/\bliquidity\b/.test(a),
     "narrative/delivery":/\b(narrative|deliver|delivery)\b/.test(a),
     "if-this-then-that scenarios":/\bif\b[\s\S]{0,500}\bthen\b|\bif price\b/.test(a),
     "opportunity path into lower timeframes":/\b(opportunity|daily|4h|1h|30m|lower timeframes)\b/.test(a),
     "invalidation":/\b(invalid|invalidation)\b/.test(a)
   };
   if(tf==="WEEKLY"){
     review.missingPoints=review.missingPoints.filter(x=>!Object.keys(covered).some(k=>String(x).toLowerCase().includes(k.toLowerCase())&&covered[k]));
     // Once Jay has explicitly assessed Weekly liquidity, VEGA must not turn
     // that assessment into a requirement to find additional liquidity.
     // Only a clear chart contradiction may make the assessment incorrect.
     if(covered["liquidity assessment"]){
       review.missingLiquidity=[];
       review.incorrectPoints=(review.incorrectPoints||[]).filter(x=>{
         const s=String(x).toLowerCase();
         const isLiquidityRecommendation=/\b(mark|identify|find|add|look for|need|should|must)\b[\s\w]{0,80}\b(liquidity|eqh|eql|equal highs|equal lows|trendline|stop[- ]?cluster|intermediate)\b/.test(s);
         const isUnsupportedAbsenceCorrection=(s.includes("no liquidity")||s.includes("don't see any equal")||s.includes("do not see any equal")||s.includes("absence")&&s.includes("liquidity"));
         const isExplicitContradiction=/\b(chart|visible|shown)\b[\s\w]{0,80}\b(contradict|does show|shows|visible liquidity|eqh|eql|equal highs|equal lows|trendline liquidity)\b/.test(s)&&!isLiquidityRecommendation;
         return !(isLiquidityRecommendation||isUnsupportedAbsenceCorrection) || isExplicitContradiction;
       });
     }
   }
   // A timeframe-specific requirement is satisfied when the transcript clearly
   // addresses it. AI recommendations are not converted into missing items.
   if(!review.missingPoints.length&&!(review.incorrectPoints||[]).length)review.status="CORRECT";
   return review;
 }
 async function reviewAnalysis(){if(state.awaitingReview)return withAnnouncement(()=>({handled:true,waiting:true,message:"I'm reviewing that now.",state:snapshot()}));const tf=current();state.awaitingReview=true;state.lastAnalysis=state.currentTranscript;save();const screen=ASTRA.modules.screen;if(!screen?.sharing){state.awaitingReview=false;save();return withAnnouncement(()=>({handled:true,message:`I'm ready to review your ${tf} analysis, but I need the chart shared and visible first. Keep the ${tf} chart on screen, then say you're finished again.`}));}const frame=screen.getFrame?.({maxWidth:1440,quality:.65});if(!frame){state.awaitingReview=false;save();return withAnnouncement(()=>({handled:true,message:`I can't see a usable ${tf} chart yet. Keep the ${tf} chart visible, then say you're finished again.`}));}const system=ASTRA.modules.trading?.strategy||{};try{const result=await ASTRA.modules.ai.ask(buildReviewPrompt(tf,state.lastAnalysis,system),{image:frame,vision:true,trading:true,topDownReview:true,skipTopDown:true,returnOnly:true,context:{timeframe:tf,role:roleFor(tf),requirements:requirementsFor(tf),analysis:state.lastAnalysis,strategySource:"Jay original detailed Trading Strategy"}});const parsed=enforceContract(tf,normalizeReview(result?.answer),state.lastAnalysis);state.lastReview={timeframe:tf,...parsed,date:new Date().toISOString()};if(parsed.status==="CORRECT"){state.completed.push({timeframe:tf,analysis:state.lastAnalysis,review:parsed,date:new Date().toISOString()});if(state.index<state.timeframes.length-1){state.index++;state.currentTranscript="";state.awaitingReview=false;save();const next=current();return withAnnouncement(()=>({handled:true,advanced:true,feedback:`${parsed.feedback} Next: ${promptFor(next)}`,state:snapshot()}));}state.active=false;state.awaitingReview=false;save();return withAnnouncement(()=>({handled:true,done:true,feedback:`${parsed.feedback} Top-down analysis is complete. Your final execution decision still requires your 15M or 5M confirmation and your trading rules.`,state:snapshot()}));}state.awaitingReview=false;save();return withAnnouncement(()=>({handled:true,waiting:true,feedback:`${parsed.feedback} WAIT — this ${tf} analysis is not complete enough to advance.`,state:snapshot()}));}catch(e){console.error("VEGA top-down review:",e);state.awaitingReview=false;save();return withAnnouncement(()=>({handled:true,message:"I couldn't complete the chart review. Stay on this timeframe, keep the chart visible, and say you're finished again.",state:snapshot()}));}}
 function handle(message){const text=String(message||"").trim();if(!text)return {handled:false};if(!state.active&&isTopDownStart(text))return start();if(!state.active)return {handled:false};if(isFinished(text))return reviewAnalysis();appendAnalysis(text);return {handled:true,listening:true,silent:true,state:snapshot()};}
 const voiceHook=setInterval(()=>{installVoiceGuard();if(voiceGuardInstalled)clearInterval(voiceHook);},250);installVoiceGuard();
 return {name:"VEGA Top-Down Coach",version:"3.3",start,stop:()=>{state.active=false;state.awaitingReview=false;allowAnnouncement=false;state.currentTranscript="";save();return snapshot()},snapshot,current,promptFor,roleFor,requirementsFor,reviewAnalysis,handle,isFinished,isTopDownStart};
})();
ASTRA.registerModule("topDownCoach",TopDownCoach);
console.log("VEGA Top-Down Coach v3.3 Loaded — timeframe contract is authoritative; recommendations cannot become missing requirements");