/* ASTRA TOP-DOWN COACH v1.8 */
const TopDownCoach=(()=>{
 const KEY="ASTRA_TOP_DOWN_SESSION",DEFAULT={active:false,timeframes:["WEEKLY","DAILY","4H","1H","15M"],index:0,completed:[],awaitingReview:false,currentTranscript:"",lastAnalysis:"",lastReview:null,updatedAt:null};
 let stored;try{stored=JSON.parse(localStorage.getItem(KEY)||"{}")}catch{stored={}}
 // Never restore an active listening session after a reload. Keeping `active:true`
 // caused every normal message (including "hello") to be swallowed as analysis.
 let state={...DEFAULT,...stored,active:false,awaitingReview:false};
 let voiceGuardInstalled=false;
 const save=()=>{state.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state))};
 const current=()=>state.timeframes[state.index]||null;
 const snapshot=()=>JSON.parse(JSON.stringify({...state,currentTimeframe:current()}));
 const normalize=t=>String(t||"").trim().toUpperCase();
 function isTopDownStart(text){const t=String(text||"").toLowerCase().replace(/[.,!?]/g," ").replace(/\s+/g," ").trim();return /\btop\s*-?\s*down(?:\s+(?:analysis|analyses|analyzing))?\b/.test(t)&&(/\b(?:i'?m|im|i am|we'?re|we are|let'?s|lets|i'?ll|ill|i will|we will|going to|gonna|want to|ready to|start|begin|do|doing|analy[sz]e|about to)\b/.test(t)||/^(?:astra\s*,?\s*)?(?:top\s*-?\s*down)/.test(t));}
 function isFinished(text){return /\b(?:i'?m|im|i am|we'?re|we are)\s+(?:finished|done)\b|\b(?:i'?m|im|i am)\s+(?:all\s+)?finished\b|\bfinished(?:\s+with)?(?:\s+(?:the\s+)?)?(?:weekly|daily|4h|1h|15m|analysis|analyzing)?\b|\b(?:that'?s|thats)\s+(?:it|all)\b|\b(?:analysis|analyzing)\s+(?:is\s+)?(?:finished|done|complete)\b/i.test(String(text||""));}
 function installVoiceGuard(){if(voiceGuardInstalled)return;const voice=ASTRA.modules.voice;if(!voice?.speak)return;const original=voice.speak.bind(voice);voice.speak=function(text,...args){if(state.active&&!state.awaitingReview)return false;return original(text,...args)};voiceGuardInstalled=true;}
 function start(timeframes){installVoiceGuard();ASTRA.modules.voice?.stopSpeaking?.({ignoreMs:1500});if(Array.isArray(timeframes)&&timeframes.length)state.timeframes=timeframes.map(normalize).filter(Boolean);state.active=true;state.index=0;state.completed=[];state.awaitingReview=false;state.currentTranscript="";state.lastAnalysis="";state.lastReview=null;ASTRA.modules.coach?.stopObserver?.();save();return {handled:true,started:true,message:`Okay, we're ready. Start with the ${current()} chart. Take your time. I won't interrupt while you're analyzing. When you're finished, say you're finished, and I'll review everything you said and check the chart.`};}
 function appendAnalysis(text){const v=String(text||"").trim();if(v){state.currentTranscript=[state.currentTranscript,v].filter(Boolean).join("\n");save();}}
 async function reviewAnalysis(){if(state.awaitingReview)return {handled:true,waiting:true,state:snapshot()};const tf=current();state.awaitingReview=true;state.lastAnalysis=state.currentTranscript;save();const screen=ASTRA.modules.screen;if(!screen?.sharing){state.awaitingReview=false;save();return {handled:true,message:`I'm ready to review your ${tf} analysis. Keep the chart shared and visible, then say you're finished again.`};}const frame=screen.getFrame?.({maxWidth:1440,quality:.6});if(!frame){state.awaitingReview=false;save();return {handled:true,message:`I can't see a usable ${tf} chart yet. Keep it visible, then say you're finished again.`};}const system=ASTRA.modules.trading?.strategy||{};const prompt=`Review Jay's ${tf} top-down analysis. Jay said:\n${state.lastAnalysis||"(No explanation captured.)"}\nInspect the shared chart. Check context, structure, liquidity, key highs/lows, supply/demand, objective, bias, confirmation, invalidation and if-then logic. Return JSON only with status CORRECT, CORRECTION or UNCLEAR, correctPoints, incorrectPoints, missingPoints, missingLiquidity, feedback, reason. Rules: ${JSON.stringify(system.rules||[])}`;try{const result=await ASTRA.modules.ai.ask(prompt,{image:frame,vision:true,trading:true,topDownReview:true,skipTopDown:true,returnOnly:true});const raw=String(result?.answer||"").trim();let parsed;try{parsed=JSON.parse(raw.replace(/^```json\s*/i,"").replace(/\s*```$/,""))}catch{parsed={status:"UNCLEAR",correctPoints:[],incorrectPoints:[],missingPoints:[],missingLiquidity:[],feedback:raw||"Let's check that again.",reason:"Unstructured review."}};state.lastReview={timeframe:tf,...parsed,date:new Date().toISOString()};if(parsed.status==="CORRECT"){state.completed.push({timeframe:tf,analysis:state.lastAnalysis,review:parsed,date:new Date().toISOString()});if(state.index<state.timeframes.length-1){state.index++;state.currentTranscript="";state.awaitingReview=false;save();return {handled:true,advanced:true,feedback:parsed.feedback||"Correct. Let's move on to the next timeframe."}}state.active=false;state.awaitingReview=false;save();return {handled:true,done:true,feedback:parsed.feedback||"Correct. Top-down analysis is complete."}}state.awaitingReview=false;save();return {handled:true,feedback:parsed.feedback||"Let's correct that before we move on."}}catch(e){state.awaitingReview=false;save();return {handled:true,message:"I couldn't complete the chart review. Stay on this timeframe and say you're finished again."}}}
 function handle(message){const text=String(message||"").trim();if(!text)return {handled:false};if(!state.active&&isTopDownStart(text))return start();if(!state.active)return {handled:false};if(isFinished(text))return reviewAnalysis();appendAnalysis(text);return {handled:true,listening:true,silent:true};}
 installVoiceGuard();return {name:"ASTRA Top-Down Coach",version:"1.8",start,stop:()=>{state.active=false;state.awaitingReview=false;save();return snapshot()},snapshot,current,reviewAnalysis,handle,isFinished,isTopDownStart};
})();
ASTRA.registerModule("topDownCoach",TopDownCoach);console.log("ASTRA Top-Down Coach v1.8 Loaded");