/* ASTRA BUTTON FIX v4.0 — voice output + dashboard actions */
window.addEventListener("DOMContentLoaded",()=>{
 const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
 const main=$(".main-area"),dashboard=$("#view-dashboard");if(!main||!dashboard)return;
 const go=n=>window.ASTRAShowView?.(n);
 const core=()=>typeof ASTRA!=="undefined"?ASTRA:null;
 const reply=text=>typeof AstraReply==="function"?AstraReply(text):console.log("VEGA:",text);
 const silentReply=text=>{const response=core()?.modules?.response,output=$("#output");if(!output)return console.log("VEGA:",text);const wrapper=document.createElement("div");wrapper.className="astra-message";wrapper.innerHTML=`<div class="message-speaker">VEGA</div><div class="message-body">${response?.format?response.format(text):`<p>${String(text).replace(/[&<>\"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",\"":"&quot;","'":"&#039;"}[m]))}</p>`}</div>`;output.appendChild(wrapper);output.scrollTop=output.scrollHeight;response?.animate?.()};
 const voiceBtn=$("#voiceBtn");
 if(voiceBtn&&!voiceBtn.dataset.voiceBound){voiceBtn.dataset.voiceBound="true";const updateVoiceButton=()=>{const active=!!core()?.modules?.voice?.status?.().outputEnabled;voiceBtn.classList.toggle("active",active);voiceBtn.textContent=active?"◉ ASTRA VOICE ON":"◉ ASTRA VOICE OFF"};voiceBtn.addEventListener("click",()=>{const v=core()?.modules?.voice;if(!v?.toggleOutput){reply("Voice output is not available yet.");return}const active=v.toggleOutput();updateVoiceButton();reply(active?"ASTRA voice output is on.":"ASTRA voice output is off.")});setTimeout(updateVoiceButton,0)}
 $$(".nav-item[data-module]").forEach(b=>{if(b.dataset.navBound)return;b.dataset.navBound="true";b.addEventListener("click",()=>go(b.dataset.module))});
 async function startTopDown(){const coach=core()?.modules?.topDownCoach;if(!coach||typeof coach.start!=="function")throw new Error("TopDownCoach unavailable");const result=await Promise.resolve(coach.start());reply(result?.message||"Okay, we're ready. Start with the WEEKLY chart.");return result;}
 function loadMicDiagnostics(){if(core()?.modules?.microphoneDiagnostics?.test)return Promise.resolve(core().modules.microphoneDiagnostics);return new Promise((resolve,reject)=>{const existing=document.querySelector('script[data-vega-mic-diagnostics="1"]');if(existing){existing.addEventListener("load",()=>resolve(core()?.modules?.microphoneDiagnostics||null),{once:true});existing.addEventListener("error",reject,{once:true});return}const s=document.createElement("script");s.src="js/system/microphoneDiagnostics.js?v=1.1";s.dataset.vegaMicDiagnostics="1";s.onload=()=>resolve(core()?.modules?.microphoneDiagnostics||null);s.onerror=reject;document.head.appendChild(s);});}
 async function runMicTest(button){button.disabled=true;const original=button.textContent;button.textContent="◌ TESTING MIC...";try{const diag=await loadMicDiagnostics();if(!diag?.test){reply("Microphone diagnostics are not available yet.");return}
   // Important: the start prompt is rendered silently so VEGA's TTS cannot occupy the microphone while the user is speaking.
   silentReply("Microphone test started. Speak normally for about three seconds so VEGA can measure the input level.");
   const r=await diag.test(3500);
   reply(r.message+(r.ok?` Input: ${r.level} · average ${r.averageDb} dB · peak ${r.peakDb} dB.`:""));
   console.log("VEGA microphone diagnostics",r);
 }catch(e){console.error("VEGA microphone diagnostics",e);reply("Microphone diagnostics failed. Please allow microphone access and try again")}finally{button.disabled=false;button.textContent=original}}
 let actions=$(".quick-actions");if(!actions){actions=document.createElement("div");actions.className="quick-actions astra-restored-actions";dashboard.appendChild(actions)}
 const ensure=(id,label,before)=>{let b=$("#"+id,actions);if(!b){b=document.createElement("button");b.id=id;b.type="button";b.textContent=label;if(before)actions.insertBefore(b,before);else actions.appendChild(b)}return b};
 ensure("newTradeBtn","＋ NEW TRADE");const topBtn=ensure("topDownBtn","◈ TOP-DOWN ANALYSIS",$("#analyzeBtn",actions));ensure("analyzeBtn","⌁ ANALYZE");ensure("journalBtn","＋ JOURNAL");ensure("screenBtn","▣ SCREEN");ensure("viewScreenBtn","◉ MARKET SCAN");ensure("watchBtn","◉ SCREEN WATCH");const micBtn=ensure("micTestBtn","◉ MIC TEST");
 const showActions=()=>{Object.assign(actions.style,{display:"flex",visibility:"visible",opacity:"1",position:"relative",zIndex:"130",width:"100%",minHeight:"40px",margin:"12px auto 0",justifyContent:"center",alignItems:"center",gap:"10px",flexWrap:"wrap"});actions.querySelectorAll("button").forEach(b=>Object.assign(b.style,{display:"inline-flex",visibility:"visible",opacity:"1",alignItems:"center",justifyContent:"center",minHeight:"34px",border:"1px solid rgba(0,194,255,.45)",background:"#052338",color:"#a9eaff",borderRadius:"18px",padding:"8px 17px",fontSize:"8px",cursor:"pointer",position:"relative",zIndex:"131"}))};
 const restoreDock=()=>{const dock=$(".conversation-dock");if(!dock)return;if(dock.parentElement!==main)main.appendChild(dock);Object.assign(dock.style,{display:"block",visibility:"visible",opacity:"1",position:"relative",zIndex:"120",width:"100%",maxWidth:"1280px",margin:"12px auto 0"})};showActions();restoreDock();setTimeout(()=>{showActions();restoreDock()},250);
 if(!topBtn.dataset.topDownBound){topBtn.dataset.topDownBound="true";topBtn.addEventListener("click",async()=>{if(topBtn.dataset.starting)return;topBtn.dataset.starting="true";const original=topBtn.textContent;topBtn.disabled=true;topBtn.textContent="◌ STARTING TOP-DOWN...";try{await startTopDown()}catch(err){console.error("ASTRA top-down button",err);reply("Top-down analysis could not start. The Top-Down Coach is not registered in ASTRA yet")}finally{topBtn.disabled=false;topBtn.textContent=original;topBtn.dataset.starting=""}})}
 if(!micBtn.dataset.micBound){micBtn.dataset.micBound="true";micBtn.addEventListener("click",()=>runMicTest(micBtn))}
 if(!actions.dataset.handlersBound){actions.dataset.handlersBound="true";actions.addEventListener("click",async e=>{const b=e.target.closest("button");if(!b||b===topBtn||b===micBtn)return;if(b.id==="newTradeBtn"){go("journal");reply("Let's log it properly. Tell me the setup, direction, reason for entry, and whether it followed your rules.")}if(b.id==="analyzeBtn"){const r=core()?.modules?.screen?.showAnalysis?.();if(!r?.ready)reply("Share your chart first, then I'll look at the setup with you.")}if(b.id==="journalBtn")go("journal");if(b.id==="screenBtn"){try{const m=core()?.modules?.screen;if(m?.sharing){m.stopCapture?.();b.classList.remove("active")}else{const r=await m?.startCapture?.();if(r!==false)b.classList.add("active")}}catch(err){console.error(err);reply("I couldn't start screen sharing. Please allow screen access when your browser asks.")}}if(b.id==="viewScreenBtn")core()?.modules?.ai?.ask?.("Give me a current market scan and tell me what is actually relevant to my trading plan.",{trading:true,analysis:true});if(b.id==="watchBtn"){const o=core()?.modules?.proactiveMarketObserver;if(!o)return reply("Screen Watch is not loaded yet.");if(o.status?.().watching){o.stop?.();b.classList.remove("active")}else{o.start?.();b.classList.add("active")}}})}
 console.log("ASTRA Button Fix v4.0 — mic calibration start is silent; result is announced after measurement");
});