/* ASTRA UI FIX v2.2
   Module views and dashboard routing only.
   Conversation submission is owned by runtimeIntegrity.js.
   Conversation layout/voice control is owned by conversationLayout.js.
*/
window.addEventListener("DOMContentLoaded", () => {
    const $ = (selector, root = document) => root.querySelector(selector);
    const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
    const data = () => ASTRA?.modules?.journal?.getData?.() || { trades: [] };
    const perf = () => ASTRA?.modules?.performance?.getData?.() || { trades: [], wins: 0, losses: 0 };
    const esc = value => String(value ?? "").replace(/[&<>"']/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[char]));
    const names = {journal:["trades","mistakes","wins","notes"],trading:["watchlist","analysis","sessions"],backtest:["overview","trades","performance"],mindset:["focus","discipline","growth"],settings:["preferences","account-&-data","system"],performance:["overview","trades","equity"]};
    const firstTab = module => names[module]?.[0] || "overview";
    const area = view => {let target=$(".tab-content-area",view);if(!target){target=document.createElement("div");target.className="tab-content-area";const tabs=$(".inner-tabs",view);if(tabs)tabs.after(target);else view.appendChild(target);}return target;};
    const rows = (trades,empty) => trades.length ? trades.slice().reverse().map((trade,index)=>`<div class="trade-line"><b>${esc(trade.pair||trade.symbol||`Trade ${trades.length-index}`)}</b><span>${esc(trade.direction||trade.side||"—")}</span><strong class="${String(trade.result).toLowerCase()==="loss"||Number(trade.pnl)<0?"negative":"positive"}">${esc(trade.result??trade.pnl??"—")}</strong><small>${esc(trade.notes||"Recorded trade")}</small></div>`).join("") : `<p class="empty-state">${empty}</p>`;
    function render(module,tab){
        const view=$("#view-"+module);if(!view)return;
        $$(".inner-tabs .tab",view).forEach((button,index)=>{if(!button.dataset.tab)button.dataset.tab=names[module]?.[index]||button.textContent.trim().toLowerCase().replace(/\s+/g,"-");button.classList.toggle("active",button.dataset.tab===tab);});
        const target=area(view);
        if(module==="journal"){const trades=data().trades||[],wins=trades.filter(t=>t.result==="win"),mistakes=trades.filter(t=>t.mistake||String(t.notes||"").toLowerCase().includes("mistake"));target.innerHTML={trades:`<div class="content-card"><h3>TRADES</h3>${rows(trades,"No trades recorded yet.")}<button class="wide-action" data-ui-action="new-trade">＋ NEW TRADE</button></div>`,mistakes:`<div class="content-card"><h3>MISTAKES</h3>${rows(mistakes,"No mistakes recorded yet. Record mistakes in your journal notes and ASTRA will surface them here.")}</div>`,wins:`<div class="content-card"><h3>WINS</h3>${rows(wins,"No winning trades recorded yet.")}</div>`,notes:`<div class="content-card"><h3>NOTES</h3>${trades.filter(t=>t.notes).map(t=>`<div class="trade-line"><b>${esc(t.pair||"NOTE")}</b><span>${esc(t.direction||"")}</span><small>${esc(t.notes)}</small></div>`).join("")||'<p class="empty-state">No journal notes yet.</p>'}</div>`}[tab]||"";}
        if(module==="trading"){target.innerHTML={watchlist:`<div class="content-card"><h3>WATCHLIST</h3><div class="watch-row"><b>XAUUSD</b><span>Live</span><strong>+0.35%</strong><em>↑</em></div><div class="watch-row"><b>GBPUSD</b><span>Live</span><strong class="negative">-0.12%</strong><em class="negative">↓</em></div><div class="watch-row"><b>EURUSD</b><span>Live</span><strong>+0.18%</strong><em>↑</em></div><div class="watch-row"><b>NAS100</b><span>Live</span><strong>+0.41%</strong><em>↑</em></div></div>`,analysis:`<div class="content-card"><h3>ANALYSIS</h3><p class="empty-state">Share your chart and ASTRA will compare what it can see with your top-down trading system.</p><button class="wide-action" data-ui-action="analyze">⌁ ANALYZE CURRENT SCREEN</button></div>`,sessions:`<div class="content-card"><h3>SESSIONS</h3><div class="metric"><span>London</span><b>7:00 AM – 11:00 AM</b></div><div class="metric"><span>New York</span><b>1:00 PM – 4:00 PM</b></div><div class="metric"><span>Review</span><b>8:30 PM – 9:00 PM</b></div></div>`}[tab]||"";}
        if(module==="backtest"){const trades=ASTRA?.modules?.backtesting?.getTrades?.()||[],insight=ASTRA?.modules?.coach?.backtestInsight?.()||{};target.innerHTML={overview:`<div class="stats-grid"><div><small>Total Trades</small><b>${insight.total??trades.length}</b></div><div><small>Win Rate</small><b>${insight.winRate??0}%</b></div><div><small>Wins</small><b>${insight.wins??0}</b></div><div><small>Net P/L</small><b>${insight.netPnl??0}</b></div></div><div class="content-card"><h3>ASTRA MENTOR</h3><p class="empty-state">Backtest mode is practice. ASTRA watches your process and will point out rule breaks without mixing them into live performance.</p><button class="wide-action" data-ui-action="backtest-coach">ASK ASTRA TO COACH THIS BACKTEST</button></div>`,trades:`<div class="content-card"><h3>BACKTEST TRADES</h3>${rows(trades,"Run a backtest to populate this view.")}<button class="wide-action" data-ui-action="backtest">OPEN BACKTEST ENGINE</button></div>`,performance:`<div class="content-card"><h3>BACKTEST PERFORMANCE</h3><div class="large-chart live"></div><p class="empty-state">Backtest-only performance. It never changes live-trading performance.</p></div>`}[tab]||"";}
        if(module==="mindset"){target.innerHTML={focus:`<div class="content-card"><h3>FOCUS</h3><label>◯ Stick to the plan</label><label>◯ Manage risk, not the trade</label><label>◯ Wait for confirmation</label><label>◯ Review before re-entering</label></div>`,discipline:`<div class="content-card"><h3>DISCIPLINE</h3><blockquote>Discipline is choosing between what you want now and what you want most.</blockquote><p class="empty-state">ASTRA tracks discipline observations from your journal and conversations.</p></div>`,growth:`<div class="content-card"><h3>GROWTH</h3><div class="stats-grid"><div><small>Focus</small><b>86%</b></div><div><small>Discipline</small><b>74%</b></div><div><small>Patience</small><b>91%</b></div></div></div>`}[tab]||"";}
        if(module==="settings"){target.innerHTML={preferences:`<div class="content-card settings-card"><h3>PREFERENCES</h3><div class="setting"><span>Theme</span><b>ASTRA Dark</b></div><div class="setting"><span>Notifications</span><button class="toggle on" type="button" aria-label="Toggle notifications"></button></div><div class="setting"><span>Sound</span><button class="toggle on" type="button" aria-label="Toggle sound"></button></div></div>`,"account-&-data":`<div class="content-card settings-card"><h3>ACCOUNT & DATA</h3><button class="wide-action" data-ui-action="demo">CONNECT DEMO ACCOUNT</button><button class="wide-action" data-ui-action="backup">BACK UP ASTRA DATA</button><p id="demoMessage" class="empty-state">Demo data stays separate from live trading data.</p><div class="setting"><span>Data Backup</span><b>Available</b></div><div class="setting"><span>Export Data</span><button class="wide-action" data-ui-action="export">EXPORT DATA</button></div></div>`,system:`<div class="content-card settings-card"><h3>SYSTEM</h3><div class="setting"><span>ASTRA Core</span><b class="positive">ONLINE</b></div><div class="setting"><span>AI Engine</span><b class="positive">OPERATIONAL</b></div><div class="setting"><span>API Bridge</span><b class="positive">CONNECTED</b></div><button class="wide-action" data-ui-action="verify">VERIFY ASTRA SYSTEM</button></div>`}[tab]||"";}
        if(module==="performance"){const performance=perf(),trades=performance.trades||[],total=trades.length,rate=total?Math.round((Number(performance.wins||0)/total)*100):0,insight=ASTRA?.modules?.coach?.performanceInsight?.()||{};target.innerHTML={overview:`<div class="stats-grid"><div><small>Total Trades</small><b>${total}</b></div><div><small>Wins</small><b class="positive">${performance.wins||0}</b></div><div><small>Losses</small><b>${performance.losses||0}</b></div><div><small>Win Rate</small><b>${rate}%</b></div></div><div class="content-card"><h3>PERFORMANCE COACH</h3><p class="empty-state">${insight.bestSetup?`Best recorded setup: ${esc(insight.bestSetup.name)} at ${insight.bestSetup.winRate}%.`:"ASTRA will surface performance patterns as your journal grows."}</p></div>`,trades:`<div class="content-card"><h3>PERFORMANCE TRADES</h3>${rows(trades,"No live trades recorded yet.")}</div>`,equity:`<div class="content-card"><h3>EQUITY CURVE</h3><div class="large-chart live"></div><div class="stats-grid"><div><small>Win Rate</small><b>${rate}%</b></div><div><small>Wins</small><b class="positive">${performance.wins||0}</b></div><div><small>Losses</small><b>${performance.losses||0}</b></div></div></div>`}[tab]||"";}
    }
    function showView(name){
        $$(".view").forEach(view=>view.classList.remove("active-view"));$("#view-"+name)?.classList.add("active-view");$$(".nav-item").forEach(button=>button.classList.toggle("active",button.dataset.module===name));
        if(name==="backtest")ASTRA.modules.coach?.setState?.("BACKTEST","backtest-view-opened");else if(name==="trading")ASTRA.modules.coach?.setState?.("MARKUP","trading-view-opened");else if(name==="journal")ASTRA.modules.coach?.setState?.("JOURNAL","journal-view-opened");else if(name==="mindset")ASTRA.modules.coach?.setState?.("REVIEW","mindset-view-opened");
        render(name,firstTab(name));
    }
    window.ASTRAShowView=showView;
    const linkCard=(selector,route)=>{const element=$(selector);if(!element||element.dataset.routeLinked)return;element.dataset.routeLinked="true";element.dataset.route=route;element.classList.add("linked-module");element.setAttribute("role","button");element.tabIndex=0;};
    linkCard(".plan-panel","dashboard");linkCard(".performance-panel","performance");linkCard(".account-panel","trading");linkCard(".risk-panel","trading");
    Object.entries(names).forEach(([module,labels])=>{const view=$("#view-"+module);if(!view)return;$$(' .inner-tabs',view).forEach(group=>{$$(".tab",group).forEach((button,index)=>{if(!button.dataset.tab)button.dataset.tab=labels[index]||button.textContent.trim().toLowerCase().replace(/\s+/g,"-");if(!button.dataset.uiBound){button.dataset.uiBound="true";button.addEventListener("click",()=>render(module,button.dataset.tab));}});});render(module,$(".inner-tabs .tab.active",view)?.dataset.tab||firstTab(module));});
    document.addEventListener("click",event=>{
        const route=event.target.closest("[data-route]");if(route&&!event.target.closest("button")){showView(route.dataset.route);return;}
        const action=event.target.closest("[data-ui-action]");if(!action)return;const name=action.dataset.uiAction;
        if(name==="new-trade"){showView("journal");AstraReply("Let's log it properly. Tell me the setup, direction, reason for entry, and whether it followed your rules.");}
        if(name==="analyze"){const result=ASTRA?.modules?.screen?.showAnalysis?.();if(!result?.ready)AstraReply("Share your chart first, then I'll look at the setup with you.");}
        if(name==="backtest"){ASTRA.modules.coach?.setState?.("BACKTEST","backtest-engine-opened");AstraReply("Backtest mode is on. I'll keep this separate from your live results and coach the process as you work.");}
        if(name==="backtest-coach"){ASTRA.modules.coach?.setState?.("BACKTEST","manual-backtest-coach");ASTRA.modules.ai?.ask?.("Coach me through this backtest like a mentor sitting beside me. Review the current backtest state and tell me the one thing I should focus on next.",{trading:true,backtest:true,context:{backtestCoachRequest:true,mentor:ASTRA.modules.coach?.mentorContext?.()}});}
        if(name==="demo"){const message=$("#demoMessage");if(message)message.textContent="Demo account area is ready. Connect a demo feed when you choose one.";}
        if(name==="backup"){ASTRA.modules.backup?.create?.();AstraReply("ASTRA data backup requested.");}
        if(name==="export"){const payload={memory:ASTRA.modules.memory?.database||null,journal:ASTRA.modules.journal?.getData?.()||null,performance:ASTRA.modules.performance?.getData?.()||null,coach:ASTRA.modules.coach?.snapshot?.()||null};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="astra-data-export.json";link.click();URL.revokeObjectURL(link.href);}
        if(name==="verify"){const verifier=ASTRA.modules.systemVerifier||ASTRA.modules.verification;if(verifier?.verifyAll){verifier.verifyAll();}else if(ASTRA.modules.verification?.verify){AstraReply("Verification Engine is online.");}else AstraReply("Verification Engine is unavailable.");}
    });
    console.log("ASTRA UI Fix v2.2 Loaded — module views + dashboard routing + mentor controls");
});
