
/* =========================================
   ASTRA UPDATE ANALYZER v2.0
========================================= */

const UpdateAnalyzer = {


    analyze(command){


        let text =
        command
        .toLowerCase()
        .replace("add","")
        .replace("create","")
        .replace("build","")
        .trim();



        let feature =
        text
        .replace(/\bmode\b/g,"")
        .trim();



        let module =
        feature
        .split(" ")
        .map(word =>
            word.charAt(0).toUpperCase()
            + word.slice(1)
        )
        .join("")
        +
        "Module";



        // Special names

        if(feature.includes("backtest")){

            module =
            "BacktestingModule";

        }


        if(feature.includes("trade replay")){

            module =
            "TradeReplayModule";

        }


        if(feature.includes("screen")){

            module =
            "ScreenIntelligenceModule";

        }


        if(feature.includes("voice")){

            module =
            "VoiceModule";

        }



        return {


            version:"1.0",

            feature:
            feature
            .replace(/\b\w/g,
            c=>c.toUpperCase()),


            module:module,


            changes:
            "Generated by ASTRA Build System"


        };


    }


};


       ASTRA.registerModule(
    "updateAnalyzer",
    UpdateAnalyzer
);

console.log(
    "ASTRA Update Analyzer v2.0 Loaded"
);


function getModuleType(feature){

    feature =
    feature.toLowerCase();


    if(feature.includes("trade")
    || feature.includes("backtest")){

        return "trading";

    }


    if(feature.includes("screen")
    || feature.includes("analysis")){

        return "analysis";

    }


    if(feature.includes("voice")
    || feature.includes("assistant")){

        return "ai";

    }


    return "core";

}

       