/* =========================================================
   ASTRA VOICE / CONVERSATION ENGINE v2.2
   Final voice transcripts use the same canonical conversation pipeline as typed input.
========================================================= */
const VoiceModule = (() => {
    const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition;
    let recognition = null, listening = false, speaking = false, restarting = false;
    let voices = [], restartTimer = null, speechQueue = [], queueRunning = false, currentUtterance = null;
    let ignoreRecognitionUntil = 0, processingTranscript = false, lastTranscript = "", lastTranscriptAt = 0;
    const STORAGE = {voice:"ASTRA_VOICE_NAME",provider:"ASTRA_VOICE_PROVIDER",rate:"ASTRA_VOICE_RATE",pitch:"ASTRA_VOICE_PITCH",ttsPath:"ASTRA_VOICE_TTS_PATH"};
    const settings = {provider:localStorage.getItem(STORAGE.provider)||"auto",voiceName:localStorage.getItem(STORAGE.voice)||"",rate:Number(localStorage.getItem(STORAGE.rate)||0.96),pitch:Number(localStorage.getItem(STORAGE.pitch)||1),ttsPath:localStorage.getItem(STORAGE.ttsPath)||"/tts"};
    const NATURAL_PATTERNS=["online (natural)","online natural","neural","natural","premium","enhanced","wavenet","studio","journey","aria","jenny","ava","samantha","karen","google us english","microsoft"];
    const VOICE_RANK=["microsoft aria online (natural)","microsoft jenny online (natural)","microsoft ava online (natural)","microsoft sara online (natural)","microsoft guy online (natural)","google us english","samantha","karen","ava","aria","jenny","daniel"];
    const supported=()=>!!Recognition;
    function loadVoices(){if(!window.speechSynthesis)return [];voices=window.speechSynthesis.getVoices()||[];return voices;}
    function voiceScore(voice){const name=String(voice?.name||"").toLowerCase(),lang=String(voice?.lang||"").toLowerCase();if(!/^en(-|_)/i.test(lang))return -1000;let score=0;if(voice.default)score+=8;if(lang==="en-us")score+=20;if(lang.startsWith("en-us"))score+=8;VOICE_RANK.forEach((p,i)=>{if(name.includes(p))score+=120-i*5;});NATURAL_PATTERNS.forEach(p=>{if(name.includes(p))score+=35;});return score;}
    function pickVoice(){loadVoices();if(settings.voiceName){const saved=voices.find(v=>v.name===settings.voiceName);if(saved)return saved;}return voices.filter(v=>/^en(-|_)/i.test(v.lang)).sort((a,b)=>voiceScore(b)-voiceScore(a))[0]||null;}
    function clearRestart(){if(restartTimer){clearTimeout(restartTimer);restartTimer=null;}restarting=false;}
    function scheduleRestart(delay=250){if(!listening||speaking||restarting||!recognition)return;restarting=true;restartTimer=setTimeout(()=>{restartTimer=null;restarting=false;if(!listening||speaking||!recognition)return;try{recognition.start();}catch(error){scheduleRestart(700);}},delay);}
    function cleanForSpeech(text){let clean=String(text??"").replace(/<[^>]*>/g," ").replace(/```[\s\S]*?```/g," ").replace(/[*_#`]/g,"").replace(/\s+/g," ").trim();return clean.replace(/\bGBP\/USD\b/gi,"British pound versus US dollar").replace(/\bEUR\/USD\b/gi,"euro versus US dollar").replace(/\bUSD\/JPY\b/gi,"US dollar versus Japanese yen").replace(/\bGBP\b/gi,"British pound").replace(/\bUSD\b/gi,"US dollar").replace(/\bEUR\b/gi,"euro").replace(/\bJPY\b/gi,"Japanese yen").replace(/\bAUD\b/gi,"Australian dollar").replace(/\bCAD\b/gi,"Canadian dollar").replace(/\bCHF\b/gi,"Swiss franc").replace(/\bNZD\b/gi,"New Zealand dollar").replace(/\b(\d+(?:\.\d+)?)%\b/g,"$1 percent").replace(/\s*\/\s*/g," versus ");}
    function splitForConversation(text){const clean=cleanForSpeech(text);if(!clean)return [];const sentences=clean.replace(/\s*\n+\s*/g,". ").match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[clean],chunks=[];let buffer="";for(const s of sentences){const part=s.trim();if(!part)continue;if((buffer+" "+part).trim().length<=190)buffer=(buffer+" "+part).trim();else{if(buffer)chunks.push(buffer);buffer=part;}}if(buffer)chunks.push(buffer);return chunks.slice(0,12);}
    function stopSpeaking(options={}){speechQueue=[];queueRunning=false;currentUtterance=null;if(window.speechSynthesis){try{window.speechSynthesis.cancel();}catch(error){}}speaking=false;ignoreRecognitionUntil=Date.now()+Number(options.ignoreMs||1000);clearRestart();}
    function nativeSpeakChunk(chunk){if(!window.speechSynthesis||!chunk)return false;const utterance=new SpeechSynthesisUtterance(chunk);currentUtterance=utterance;const voice=pickVoice();if(voice)utterance.voice=voice;utterance.rate=Math.max(.82,Math.min(1.08,settings.rate));utterance.pitch=Math.max(.88,Math.min(1.12,settings.pitch));utterance.volume=1;utterance.onstart=()=>{speaking=true;};utterance.onend=()=>{if(currentUtterance!==utterance)return;currentUtterance=null;const next=speechQueue.shift();if(next){setTimeout(()=>nativeSpeakChunk(next.text),next.pause);return;}queueRunning=false;speaking=false;ignoreRecognitionUntil=Date.now()+1100;if(listening&&recognition)scheduleRestart(650);};utterance.onerror=()=>{if(currentUtterance!==utterance)return;currentUtterance=null;speechQueue=[];queueRunning=false;speaking=false;ignoreRecognitionUntil=Date.now()+1100;if(listening&&recognition)scheduleRestart(650);};try{window.speechSynthesis.speak(utterance);return true;}catch(error){console.error("ASTRA native voice output:",error);return false;}}
    async function remoteSpeak(text){const api=ASTRA.modules.api;if(!api?.status?.().configured)return false;try{const data=await api.request(settings.ttsPath,{method:"POST",body:JSON.stringify({text,voice:settings.voiceName||null,provider:"natural",format:"mp3",instructions:"Conversational, warm, clear, natural pacing. Do not sound like a command reader.",responseFormat:"json"})});const audioUrl=data?.audioUrl||data?.url||data?.audio_url,audioData=data?.audioData||data?.audio||data?.audio_base64;if(!audioUrl&&!audioData)return false;const audio=new Audio(audioUrl||`data:audio/mpeg;base64,${audioData}`);speaking=true;ignoreRecognitionUntil=Date.now()+1200;await audio.play();await new Promise(resolve=>{audio.onended=resolve;audio.onerror=resolve;});speaking=false;ignoreRecognitionUntil=Date.now()+1100;if(listening&&recognition)scheduleRestart(650);return true;}catch(error){console.warn("ASTRA remote TTS unavailable; using native voice:",error);speaking=false;return false;}}
    async function speak(text){if(!text)return false;const chunks=splitForConversation(text);if(!chunks.length)return false;stopSpeaking({ignoreMs:800});if((settings.provider==="gateway"||settings.provider==="auto")&&await remoteSpeak(cleanForSpeech(text)))return true;if(!window.speechSynthesis)return false;speechQueue=chunks.slice(1).map((text,index)=>({text,pause:/[?]$/.test(chunks[index])?330:210}));queueRunning=true;return nativeSpeakChunk(chunks[0]);}
    async function dispatchTranscript(text){const transcript=String(text||"").trim();if(!transcript)return false;const now=Date.now();if(processingTranscript)return false;if(transcript.toLowerCase()===lastTranscript.toLowerCase()&&now-lastTranscriptAt<1200)return false;processingTranscript=true;lastTranscript=transcript;lastTranscriptAt=now;try{ASTRA.modules.response?.user?.(transcript);const command=ASTRA.modules.command;let handled=false;
        if(command?.process){try{handled=await Promise.resolve(command.process(transcript));}catch(routerError){console.error("ASTRA voice command router:",routerError);handled=false;}}
        if(!handled&&ASTRA.modules.ai?.ask){await Promise.resolve(ASTRA.modules.ai.ask(transcript));handled=true;}
        if(!handled)throw new Error("No conversation handler accepted the voice transcript");
        return true;
    }catch(error){console.error("ASTRA voice transcript routing:",error);if(typeof AstraReply==="function")AstraReply("I heard you, but I couldn't process that request. Please try again.");return false;}finally{processingTranscript=false;}}
    function start(){if(!supported()){AstraReply("Voice recognition is not supported by this browser.");return false;}if(listening)return true;loadVoices();clearRestart();ignoreRecognitionUntil=Date.now()+900;recognition=new Recognition();recognition.continuous=true;recognition.interimResults=true;recognition.lang="en-US";recognition.maxAlternatives=1;recognition.onresult=event=>{for(let i=event.resultIndex;i<event.results.length;i++){const result=event.results[i],text=result[0]?.transcript?.trim();if(speaking||Date.now()<ignoreRecognitionUntil)continue;if(!result.isFinal||!text)continue;dispatchTranscript(text);}};recognition.onerror=event=>{console.warn("ASTRA voice recognition:",event.error);if(listening&&event.error!=="not-allowed"&&event.error!=="service-not-allowed")scheduleRestart(350);};recognition.onend=()=>{if(listening&&!speaking)scheduleRestart(650);};try{listening=true;recognition.start();AstraReply("Voice is ready.");return true;}catch(error){console.error("ASTRA voice start:",error);listening=false;recognition=null;return false;}}
    function stop(){listening=false;clearRestart();stopSpeaking({ignoreMs:500});if(recognition){try{recognition.stop();}catch(error){}recognition=null;}AstraReply("Voice is off.");}
    const toggle=()=>listening?(stop(),false):start();
    function setVoice(name){loadVoices();const voice=voices.find(v=>v.name===name);if(!voice)return false;settings.voiceName=voice.name;localStorage.setItem(STORAGE.voice,voice.name);return true;}
    function setProvider(provider){const value=String(provider||"auto").toLowerCase();if(!["auto","native","gateway"].includes(value))return false;settings.provider=value;localStorage.setItem(STORAGE.provider,value);return true;}
    function setRate(rate){const value=Number(rate);if(!Number.isFinite(value))return false;settings.rate=Math.max(.82,Math.min(1.08,value));localStorage.setItem(STORAGE.rate,String(settings.rate));return true;}
    function setPitch(pitch){const value=Number(pitch);if(!Number.isFinite(value))return false;settings.pitch=Math.max(.88,Math.min(1.12,value));localStorage.setItem(STORAGE.pitch,String(settings.pitch));return true;}
    function getVoices(){loadVoices();return voices.filter(v=>/^en(-|_)/i.test(v.lang)).map(v=>({name:v.name,lang:v.lang,default:v.default,naturalScore:voiceScore(v)})).sort((a,b)=>b.naturalScore-a.naturalScore);}
    function status(){const voice=pickVoice();return {supported:supported(),listening,speaking,restarting,processingTranscript,provider:settings.provider,voice:voice?.name||null,voiceNaturalScore:voice?voiceScore(voice):null,rate:settings.rate,pitch:settings.pitch,ttsPath:settings.ttsPath,gatewayConfigured:!!ASTRA.modules.api?.status?.().configured,conversationalPacing:true,interruptionProtection:true};}
    if(window.speechSynthesis)window.speechSynthesis.onvoiceschanged=loadVoices;
    return {name:"Voice Conversation Engine",version:"2.2",supported,start,stop,toggle,speak,stopSpeaking,dispatchTranscript,setVoice,setProvider,setRate,setPitch,getVoices,status};
})();
ASTRA.registerModule("voice",VoiceModule);