/* =========================================================
   ASTRA VOICE / CONVERSATION ENGINE v2.7
   Push-to-talk microphone + independent speech output control.
   Improvement: use recognition alternatives and a trading vocabulary
   scorer so common domain terms are less likely to be replaced by
   unrelated words before command routing.
========================================================= */
const VoiceModule = (() => {
    const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition;
    let recognition=null,listening=false,speaking=false,restarting=false,pushToTalk=false;
    let voices=[],restartTimer=null,speechQueue=[],queueRunning=false,currentUtterance=null;
    let ignoreRecognitionUntil=0,processingTranscript=false,lastTranscript="",lastTranscriptAt=0;
    let pendingTranscript="",pendingTimer=null;
    const STORAGE={voice:"ASTRA_VOICE_NAME",provider:"ASTRA_VOICE_PROVIDER",rate:"ASTRA_VOICE_RATE",pitch:"ASTRA_VOICE_PITCH",ttsPath:"ASTRA_VOICE_TTS_PATH",output:"ASTRA_VOICE_OUTPUT"};
    const settings={provider:localStorage.getItem(STORAGE.provider)||"auto",voiceName:localStorage.getItem(STORAGE.voice)||"",rate:Number(localStorage.getItem(STORAGE.rate)||0.96),pitch:Number(localStorage.getItem(STORAGE.pitch)||1),ttsPath:localStorage.getItem(STORAGE.ttsPath)||"/tts",output:localStorage.getItem(STORAGE.output)!=="off"};
    const TRADING_TERMS=["weekly","daily","four hour","4h","one hour","1h","thirty minute","30m","fifteen minute","15m","five minute","5m","recent leg","leg of price action","price action","market structure","structure","higher timeframe","lower timeframe","supply and demand","supply","demand","liquidity","equal highs","equal lows","imbalance","displacement","momentum","narrative","delivery","fractal","break of structure","bos","change of character","choch","confirmation","invalidation","scenario","buy","sell","entry","target","range","swing high","swing low","high","low"];
    const supported=()=>!!Recognition;

    function normalizeTradingTranscript(text){let v=String(text||"").trim();if(!v)return "";const r=[[/\btop[ -]down analys(?:is|es)\b/gi,"top-down analysis"],[/\bcap[ -]?down analysis\b/gi,"top-down analysis"],[/\bsupply (?:in|n) demand\b/gi,"supply and demand"],[/\bliquid (?:itty|city)\b/gi,"liquidity"],[/\bliquidities\b/gi,"liquidity"],[/\bfracture(?:al)?\b/gi,"fractal"],[/\bfractual\b/gi,"fractal"],[/\bconfirm nation\b/gi,"confirmation"],[/\bweek lee\b/gi,"weekly"],[/\bweakly\b/gi,"weekly"],[/\blegal(?=\s+(?:price|market|structure|leg|of)\b)/gi,"leg"],[/\bfour\s*hour(?:s)?\b/gi,"4H"],[/\bone\s*hour(?:s)?\b/gi,"1H"],[/\bthirty\s*minute(?:s)?\b/gi,"30M"],[/\bfifteen\s*minute(?:s)?\b/gi,"15M"],[/\bfive\s*minute(?:s)?\b/gi,"5M"],[/\bI(?:'| a)m finished\b/gi,"I'm finished"],[/\bI'm finish\b/gi,"I'm finished"]];r.forEach(([a,b])=>v=v.replace(a,b));return v.replace(/\s+/g," ").trim();}
    function scoreRecognitionCandidate(text){const s=String(text||"").toLowerCase();if(!s)return -Infinity;let score=0;for(const term of TRADING_TERMS){if(s.includes(term))score+=term.length>=7?3:2;}if(/\b(weekly|daily|4h|1h|30m|15m|5m)\b/.test(s))score+=3;if(/\b(price action|market|structure|liquidity|supply|demand|narrative|confirmation|invalidation)\b/.test(s))score+=2;return score;}
    function chooseRecognitionCandidate(result){const candidates=[];for(let i=0;i<Math.min(result?.length||0,3);i++){const t=result[i]?.transcript?.trim();if(t)candidates.push({text:t,confidence:Number(result[i]?.confidence||0),score:scoreRecognitionCandidate(t),index:i});}if(!candidates.length)return "";candidates.sort((a,b)=>{const domain=b.score-a.score;if(domain)return domain;return b.confidence-a.confidence;});return candidates[0].text;}
    function loadVoices(){voices=window.speechSynthesis?.getVoices?.()||[];return voices;}
    function pickVoice(){loadVoices();if(settings.voiceName){const s=voices.find(v=>v.name===settings.voiceName);if(s)return s;}return voices.find(v=>/^en-us/i.test(v.lang))||voices.find(v=>/^en/i.test(v.lang))||voices[0]||null;}
    function clearRestart(){if(restartTimer){clearTimeout(restartTimer);restartTimer=null;}restarting=false;}
    function clearPendingTranscript(){if(pendingTimer){clearTimeout(pendingTimer);pendingTimer=null;}pendingTranscript="";}
    function scheduleRestart(delay=400){if(!listening||speaking||!pushToTalk||restarting||!recognition)return;restarting=true;restartTimer=setTimeout(()=>{restarting=false;restartTimer=null;if(!listening||speaking||!pushToTalk||!recognition)return;try{recognition.start();}catch(e){scheduleRestart(800);}},delay);}
    function cleanForSpeech(t){return String(t??"").replace(/<[^>]*>/g," ").replace(/```[\s\S]*?```/g," ").replace(/[*_#`]/g,"").replace(/\bGBP\/USD\b/gi,"British pound versus US dollar").replace(/\bEUR\/USD\b/gi,"euro versus US dollar").replace(/\bUSD\/JPY\b/gi,"US dollar versus Japanese yen").replace(/\b4H\b/gi,"four hour").replace(/\b1H\b/gi,"one hour").replace(/\b30M\b/gi,"thirty minute").replace(/\b15M\b/gi,"fifteen minute").replace(/\b5M\b/gi,"five minute").replace(/\s+/g," ").trim();}
    function splitForConversation(t){const s=cleanForSpeech(t);if(!s)return[];const a=s.match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[s],out=[];let b="";for(const x of a){const p=x.trim();if(!p)continue;if((b+" "+p).trim().length<=220)b=(b+" "+p).trim();else{if(b)out.push(b);b=p;}}if(b)out.push(b);return out;}
    function stopSpeaking(o={}){speechQueue=[];queueRunning=false;currentUtterance=null;try{window.speechSynthesis?.cancel?.();}catch(e){}speaking=false;ignoreRecognitionUntil=Date.now()+Number(o.ignoreMs||900);clearRestart();}
    function nativeSpeakChunk(chunk){if(!window.speechSynthesis||!chunk)return false;const synth=window.speechSynthesis;const u=new SpeechSynthesisUtterance(chunk);currentUtterance=u;const v=pickVoice();if(v)u.voice=v;u.rate=Math.max(.82,Math.min(1.08,settings.rate));u.pitch=Math.max(.88,Math.min(1.12,settings.pitch));u.volume=1;u.onstart=()=>{speaking=true;};const done=()=>{if(currentUtterance!==u)return;currentUtterance=null;const n=speechQueue.shift();if(n){setTimeout(()=>nativeSpeakChunk(n.text),n.pause);return;}queueRunning=false;speaking=false;ignoreRecognitionUntil=Date.now()+900;if(pushToTalk&&listening)scheduleRestart(600);};u.onend=done;u.onerror=done;try{synth.cancel();synth.resume?.();setTimeout(()=>{try{synth.resume?.();synth.speak(u);}catch(e){done();}},60);return true;}catch(e){console.error("ASTRA native speech failed",e);done();return false;}}
    async function remoteSpeak(text){const api=ASTRA.modules.api;if(!api?.status?.().configured)return false;try{const data=await Promise.race([api.request(settings.ttsPath,{method:"POST",body:JSON.stringify({text,format:"mp3"})}),new Promise((_,rej)=>setTimeout(()=>rej(new Error("TTS timeout")),5000))]);const url=data?.audioUrl||data?.url||data?.audio_url;if(!url)return false;const audio=new Audio(url);speaking=true;await audio.play();await new Promise(r=>{audio.onended=r;audio.onerror=r;});speaking=false;return true;}catch(e){speaking=false;return false;}}
    async function speak(text){if(!settings.output)return false;const chunks=splitForConversation(text);if(!chunks.length)return false;stopSpeaking({ignoreMs:700});if(settings.provider==="gateway"){const ok=await remoteSpeak(cleanForSpeech(text));if(ok)return true;}speechQueue=chunks.slice(1).map((text,i)=>({text,pause:i===0?220:160}));queueRunning=true;return nativeSpeakChunk(chunks[0]);}
    function commitTranscript(text){const transcript=normalizeTradingTranscript(text);if(!transcript)return false;const now=Date.now();if(processingTranscript||(transcript.toLowerCase()===lastTranscript.toLowerCase()&&now-lastTranscriptAt<1200))return false;processingTranscript=true;lastTranscript=transcript;lastTranscriptAt=now;try{ASTRA.modules.response?.user?.(transcript);let handled=false;if(ASTRA.modules.command?.process)handled=ASTRA.modules.command.process(transcript);if(handled&&typeof handled.then==="function"){return handled.then(ok=>{if(!ok&&ASTRA.modules.ai?.ask)return ASTRA.modules.ai.ask(transcript).then(()=>true);return !!ok;}).catch(e=>{console.error("ASTRA voice routing",e);return false;}).finally(()=>{processingTranscript=false;});}if(!handled&&ASTRA.modules.ai?.ask)return ASTRA.modules.ai.ask(transcript).then(()=>true).catch(e=>{console.error("ASTRA voice AI routing",e);return false;}).finally(()=>{processingTranscript=false;});processingTranscript=false;return !!handled;}catch(e){console.error("ASTRA voice routing",e);processingTranscript=false;return false;}}
    function flushPendingTranscript(){const text=pendingTranscript.trim();clearPendingTranscript();if(text)commitTranscript(text);}
    function appendFinalTranscript(text){const t=String(text||"").trim();if(!t)return;pendingTranscript=[pendingTranscript,t].filter(Boolean).join(" ");if(pendingTimer)clearTimeout(pendingTimer);pendingTimer=setTimeout(flushPendingTranscript,320);}
    function buildRecognition(){if(!supported())return null;const r=new Recognition();r.continuous=true;r.interimResults=true;r.lang="en-US";r.maxAlternatives=3;r.onresult=e=>{for(let i=e.resultIndex;i<e.results.length;i++){const x=e.results[i];if(speaking||Date.now()<ignoreRecognitionUntil||!x)continue;if(x.isFinal){const t=chooseRecognitionCandidate(x);if(t)appendFinalTranscript(t);}}};r.onerror=e=>{if(listening&&pushToTalk&&e.error!=="not-allowed"&&e.error!=="service-not-allowed")scheduleRestart(400);};r.onend=()=>{if(pendingTranscript)flushPendingTranscript();if(listening&&pushToTalk&&!speaking)scheduleRestart(650);};return r;}
    function start(){if(!supported()){AstraReply("Voice recognition is not supported by this browser.");return false;}if(listening)return true;loadVoices();clearRestart();clearPendingTranscript();ignoreRecognitionUntil=Date.now()+300;recognition=buildRecognition();try{listening=true;pushToTalk=true;recognition.start();return true;}catch(e){listening=false;pushToTalk=false;recognition=null;return false;}}
    function stop(){pushToTalk=false;listening=false;clearRestart();clearPendingTranscript();stopSpeaking({ignoreMs:400});try{recognition?.stop?.();}catch(e){}recognition=null;}
    function pushStart(){if(!supported())return false;if(!listening)start();if(!recognition)return false;pushToTalk=true;clearRestart();try{recognition.start();}catch(e){}return true;}
    function pushStop(){pushToTalk=false;clearRestart();flushPendingTranscript();try{recognition?.stop?.();}catch(e){}listening=false;}
    function toggle(){return listening?(stop(),false):start();}
    function setOutput(enabled){settings.output=!!enabled;localStorage.setItem(STORAGE.output,settings.output?"on":"off");if(!settings.output)stopSpeaking({ignoreMs:300});return settings.output;}
    function toggleOutput(){return setOutput(!settings.output);}
    function setVoice(n){loadVoices();const v=voices.find(x=>x.name===n);if(!v)return false;settings.voiceName=v.name;localStorage.setItem(STORAGE.voice,v.name);return true;}
    function setProvider(p){p=String(p||"auto").toLowerCase();if(!["auto","native","gateway"].includes(p))return false;settings.provider=p;localStorage.setItem(STORAGE.provider,p);return true;}
    function setRate(r){r=Number(r);if(!Number.isFinite(r))return false;settings.rate=Math.max(.82,Math.min(1.08,r));localStorage.setItem(STORAGE.rate,String(settings.rate));return true;}
    function setPitch(p){p=Number(p);if(!Number.isFinite(p))return false;settings.pitch=Math.max(.88,Math.min(1.12,p));localStorage.setItem(STORAGE.pitch,String(settings.pitch));return true;}
    function getVoices(){loadVoices();return voices.filter(v=>/^en/i.test(v.lang)).map(v=>({name:v.name,lang:v.lang,default:v.default}));}
    function status(){const v=pickVoice();return {supported:supported(),listening,pushToTalk,speaking,outputEnabled:settings.output,provider:settings.provider,voice:v?.name||null,voiceCount:voices.length,tradingSpeechNormalization:true,transcriptBuffering:true,alternativeCandidateScoring:true};}
    function bindKeyboard(){if(window.__ASTRA_PUSH_TO_TALK_BOUND__)return;window.__ASTRA_PUSH_TO_TALK_BOUND__=true;window.addEventListener("keydown",e=>{if(e.repeat||e.key.toLowerCase()!=="v")return;const tag=e.target?.tagName?.toLowerCase();if(tag==="input"||tag==="textarea"||e.target?.isContentEditable)return;e.preventDefault();pushStart();});window.addEventListener("keyup",e=>{if(e.key.toLowerCase()!=="v")return;const tag=e.target?.tagName?.toLowerCase();if(tag==="input"||tag==="textarea"||e.target?.isContentEditable)return;e.preventDefault();pushStop();});}
    if(window.speechSynthesis){window.speechSynthesis.onvoiceschanged=loadVoices;setTimeout(loadVoices,0);}
    setTimeout(bindKeyboard,0);
    return {name:"Voice Conversation Engine",version:"2.7",supported,start,stop,toggle,pushStart,pushStop,speak,stopSpeaking,dispatchTranscript:commitTranscript,normalizeTradingTranscript,setVoice,setProvider,setRate,setPitch,setOutput,toggleOutput,getVoices,status};
})();
ASTRA.registerModule("voice",VoiceModule);