/* =========================================================
   ASTRA VOICE / CONVERSATION ENGINE v2.4
   Reliable browser speech output + trading-aware recognition.
========================================================= */
const VoiceModule = (() => {
    const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition;
    let recognition=null,listening=false,speaking=false,restarting=false;
    let voices=[],restartTimer=null,speechQueue=[],queueRunning=false,currentUtterance=null;
    let ignoreRecognitionUntil=0,processingTranscript=false,lastTranscript="",lastTranscriptAt=0;
    const STORAGE={voice:"ASTRA_VOICE_NAME",provider:"ASTRA_VOICE_PROVIDER",rate:"ASTRA_VOICE_RATE",pitch:"ASTRA_VOICE_PITCH",ttsPath:"ASTRA_VOICE_TTS_PATH"};
    const settings={provider:localStorage.getItem(STORAGE.provider)||"auto",voiceName:localStorage.getItem(STORAGE.voice)||"",rate:Number(localStorage.getItem(STORAGE.rate)||0.96),pitch:Number(localStorage.getItem(STORAGE.pitch)||1),ttsPath:localStorage.getItem(STORAGE.ttsPath)||"/tts"};
    const supported=()=>!!Recognition;

    function normalizeTradingTranscript(text){let v=String(text||"").trim();if(!v)return "";const r=[[/\btop[ -]down analys(?:is|es)\b/gi,"top-down analysis"],[/\bcap[ -]?down analysis\b/gi,"top-down analysis"],[/\bsupply (?:in|n) demand\b/gi,"supply and demand"],[/\bliquid (?:itty|city)\b/gi,"liquidity"],[/\bliquidities\b/gi,"liquidity"],[/\bfracture(?:al)?\b/gi,"fractal"],[/\bfractual\b/gi,"fractal"],[/\bconfirm nation\b/gi,"confirmation"],[/\bweek lee\b/gi,"weekly"],[/\bweakly\b/gi,"weekly"],[/\bfour|for hour(?:s)?\b/gi,"4H"],[/\bone hour(?:s)?\b/gi,"1H"],[/\bthirty minute(?:s)?\b/gi,"30M"],[/\bfifteen|fifty minute(?:s)?\b/gi,"15M"],[/\bfive minute(?:s)?\b/gi,"5M"],[/\bI(?:'| a)m finished\b/gi,"I'm finished"],[/\bI'm finish\b/gi,"I'm finished"]];r.forEach(([a,b])=>v=v.replace(a,b));return v.replace(/\s+/g," ").trim();}
    function loadVoices(){voices=window.speechSynthesis?.getVoices?.()||[];return voices;}
    function pickVoice(){loadVoices();if(settings.voiceName){const s=voices.find(v=>v.name===settings.voiceName);if(s)return s;}return voices.find(v=>/^en-us/i.test(v.lang))||voices.find(v=>/^en/i.test(v.lang))||voices[0]||null;}
    function clearRestart(){if(restartTimer){clearTimeout(restartTimer);restartTimer=null;}restarting=false;}
    function scheduleRestart(delay=400){if(!listening||speaking||restarting||!recognition)return;restarting=true;restartTimer=setTimeout(()=>{restarting=false;restartTimer=null;if(!listening||speaking||!recognition)return;try{recognition.start();}catch(e){scheduleRestart(800);}},delay);}
    function cleanForSpeech(t){return String(t??"").replace(/<[^>]*>/g," ").replace(/```[\s\S]*?```/g," ").replace(/[*_#`]/g,"").replace(/\bGBP\/USD\b/gi,"British pound versus US dollar").replace(/\bEUR\/USD\b/gi,"euro versus US dollar").replace(/\bUSD\/JPY\b/gi,"US dollar versus Japanese yen").replace(/\b4H\b/gi,"four hour").replace(/\b1H\b/gi,"one hour").replace(/\b30M\b/gi,"thirty minute").replace(/\b15M\b/gi,"fifteen minute").replace(/\b5M\b/gi,"five minute").replace(/\s+/g," ").trim();}
    function splitForConversation(t){const s=cleanForSpeech(t);if(!s)return[];const a=s.match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[s],out=[];let b="";for(const x of a){const p=x.trim();if(!p)continue;if((b+" "+p).trim().length<=220)b=(b+" "+p).trim();else{if(b)out.push(b);b=p;}}if(b)out.push(b);return out;}
    function stopSpeaking(o={}){speechQueue=[];queueRunning=false;currentUtterance=null;try{window.speechSynthesis?.cancel?.();}catch(e){}speaking=false;ignoreRecognitionUntil=Date.now()+Number(o.ignoreMs||900);clearRestart();}
    function nativeSpeakChunk(chunk){if(!window.speechSynthesis||!chunk)return false;const synth=window.speechSynthesis;const u=new SpeechSynthesisUtterance(chunk);currentUtterance=u;const v=pickVoice();if(v)u.voice=v;u.rate=Math.max(.82,Math.min(1.08,settings.rate));u.pitch=Math.max(.88,Math.min(1.12,settings.pitch));u.volume=1;u.onstart=()=>{speaking=true;};const done=()=>{if(currentUtterance!==u)return;currentUtterance=null;const n=speechQueue.shift();if(n){setTimeout(()=>nativeSpeakChunk(n.text),n.pause);return;}queueRunning=false;speaking=false;ignoreRecognitionUntil=Date.now()+900;if(listening)scheduleRestart(600);};u.onend=done;u.onerror=done;try{synth.cancel();synth.resume?.();setTimeout(()=>{try{synth.resume?.();synth.speak(u);}catch(e){done();}},60);return true;}catch(e){console.error("ASTRA native speech failed",e);done();return false;}}
    async function remoteSpeak(text){const api=ASTRA.modules.api;if(!api?.status?.().configured)return false;try{const data=await Promise.race([api.request(settings.ttsPath,{method:"POST",body:JSON.stringify({text,format:"mp3"})}),new Promise((_,rej)=>setTimeout(()=>rej(new Error("TTS timeout")),5000))]);const url=data?.audioUrl||data?.url||data?.audio_url;if(!url)return false;const audio=new Audio(url);speaking=true;await audio.play();await new Promise(r=>{audio.onended=r;audio.onerror=r;});speaking=false;return true;}catch(e){speaking=false;return false;}}
    async function speak(text){const chunks=splitForConversation(text);if(!chunks.length)return false;stopSpeaking({ignoreMs:700});
        // Browser speech is the reliable default. Remote TTS is only used when explicitly selected.
        if(settings.provider==="gateway"){const ok=await remoteSpeak(cleanForSpeech(text));if(ok)return true;}
        speechQueue=chunks.slice(1).map((text,i)=>({text,pause:i===0?220:160}));queueRunning=true;return nativeSpeakChunk(chunks[0]);}
    async function dispatchTranscript(text){const transcript=normalizeTradingTranscript(text);if(!transcript)return false;const now=Date.now();if(processingTranscript||(transcript.toLowerCase()===lastTranscript.toLowerCase()&&now-lastTranscriptAt<1200))return false;processingTranscript=true;lastTranscript=transcript;lastTranscriptAt=now;try{ASTRA.modules.response?.user?.(transcript);let handled=false;if(ASTRA.modules.command?.process)handled=await Promise.resolve(ASTRA.modules.command.process(transcript));if(!handled&&ASTRA.modules.ai?.ask){await ASTRA.modules.ai.ask(transcript);handled=true;}return handled;}catch(e){console.error("ASTRA voice routing",e);AstraReply?.("I heard you, but I couldn't process that request.");return false;}finally{processingTranscript=false;}}
    function start(){if(!supported()){AstraReply("Voice recognition is not supported by this browser.");return false;}if(listening)return true;loadVoices();clearRestart();ignoreRecognitionUntil=Date.now()+800;recognition=new Recognition();recognition.continuous=true;recognition.interimResults=true;recognition.lang="en-US";recognition.maxAlternatives=3;recognition.onresult=e=>{for(let i=e.resultIndex;i<e.results.length;i++){const r=e.results[i],t=r[0]?.transcript?.trim();if(speaking||Date.now()<ignoreRecognitionUntil||!r.isFinal||!t)continue;dispatchTranscript(t);}};recognition.onerror=e=>{if(listening&&e.error!=="not-allowed"&&e.error!=="service-not-allowed")scheduleRestart(400);};recognition.onend=()=>{if(listening&&!speaking)scheduleRestart(650);};try{listening=true;recognition.start();AstraReply("Voice is ready.");return true;}catch(e){listening=false;recognition=null;return false;}}
    function stop(){listening=false;clearRestart();stopSpeaking({ignoreMs:400});try{recognition?.stop?.();}catch(e){}recognition=null;AstraReply("Voice is off.");}
    const toggle=()=>listening?(stop(),false):start();
    function setVoice(n){loadVoices();const v=voices.find(x=>x.name===n);if(!v)return false;settings.voiceName=v.name;localStorage.setItem(STORAGE.voice,v.name);return true;}
    function setProvider(p){p=String(p||"auto").toLowerCase();if(!["auto","native","gateway"].includes(p))return false;settings.provider=p;localStorage.setItem(STORAGE.provider,p);return true;}
    function setRate(r){r=Number(r);if(!Number.isFinite(r))return false;settings.rate=Math.max(.82,Math.min(1.08,r));localStorage.setItem(STORAGE.rate,String(settings.rate));return true;}
    function setPitch(p){p=Number(p);if(!Number.isFinite(p))return false;settings.pitch=Math.max(.88,Math.min(1.12,p));localStorage.setItem(STORAGE.pitch,String(settings.pitch));return true;}
    function getVoices(){loadVoices();return voices.filter(v=>/^en/i.test(v.lang)).map(v=>({name:v.name,lang:v.lang,default:v.default}));}
    function status(){const v=pickVoice();return {supported:supported(),listening,speaking,provider:settings.provider,voice:v?.name||null,voiceCount:voices.length,tradingSpeechNormalization:true};}
    if(window.speechSynthesis){window.speechSynthesis.onvoiceschanged=loadVoices;setTimeout(loadVoices,0);}
    return {name:"Voice Conversation Engine",version:"2.4",supported,start,stop,toggle,speak,stopSpeaking,dispatchTranscript,normalizeTradingTranscript,setVoice,setProvider,setRate,setPitch,getVoices,status};
})();
ASTRA.registerModule("voice",VoiceModule);